### ISSUE TITLE
Error when trying to scan a world

### ISSUE THREAD

**Issue by JavoxDub** [Fenixin/Minecraft-Region-Fixer#100]
Good night. I'm trying to scan my worlds and I can't since it appears the following message:

Traceback (most recent call last):
  File "regionfixer.py", line 29, in <module>
    from regionfixer_core import world
  File "/home/admin/creativo/fixer/regionfixer_core/world.py", line 26, in <module>
    from .util import table
  File "/home/admin/creativo/fixer/regionfixer_core/util.py", line 27, in <module>
    from . import world
ImportError: cannot import name world

I've tried different versions and no result. The world is loaded on a 1.14.4 PaperMC server.

Using Python on a Linux dedicated server.

Thanks and I'll be waiting for an answer.

Regards :D

**Comment by Fenixin** [comment]
Hello!

Could you please post:
- command used to run regionfixer
- python version (you need at least python 3.7)
- regionfixer version

Also, sorry, but I don't know what a papermc servre is.

**Comment by JavoxDub** [comment]
○ python regionfixer.py --dc /home/admin/creativo/Parcelas
○ Python v3.8
○ Latest version of RegionFixer (0.3.2)

I meant that the world is hosted on a PaperMC server (Spigot fork).

**Comment by Fenixin** [comment]
Could you please make sure you are using python 3? If I write `python` in my linux system it runs version 2. In order to run python 3 I need to write `python3`. Please try writing `python --version` and `python3 --version` to check this.

**Comment by eltron247** [comment]
I'm having the same issue. Python 3.7.1

**Comment by eltron247** [comment]
I think I solved my issue. You must specify the script to be run by python.
IE:
>python regionfixer.py -p 4 c:\Users\User\Downloads\Minecraft_TMP\world_new
NOT:
>regionfixer.py -p 4 c:\Users\User\Downloads\Minecraft_TMP\world_new

**Comment by JavoxDub** [comment]
I've fixed the issue. The problem was that I wasn't specifying the python version. Using **python3.7 regionfixer.py (path)** has solved this.
