### ISSUE TITLE
"Ops! Something went really wrong and regionfixer crashed."

### ISSUE THREAD

**Issue by preceptor-teeth** [Fenixin/Minecraft-Region-Fixer#102]
When trying to scan my modded world, this error appears:

> Welcome to Region Fixer!
(version: 0.3.2)

############################################################
############################################################

World info:
There are 905 region files, 20 player files and 408 data files in the world directory.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
20 of 20|########################################################|Time: 0:00:00

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
95 of 408|############                                           |ETA:  0:00:01

Ops! Something went really wrong and regionfixer crashed.

Bug report:

**********
*** Exception while scanning:
*** inventory-bludan-2020-01-18_01.42.34-death-0.dat
**********
*** Printing the child's traceback:
*** Exception:<class 'EOFError'>Compressed file ended before the end-of-stream marker was reached
**********
*** File I:\Minecraft-Region-Fixer-master\regionfixer_core\scan.py, line 618, in scan_data
***   _ = nbt.NBTFile(filename=s.path)**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 628, in __init__
***   self.parse_file()**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 655, in parse_file
***   self._parse_buffer(self.file)**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 493, in _parse_buffer
***   tag._parse_buffer(buffer)**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 493, in _parse_buffer
***   tag._parse_buffer(buffer)**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 404, in _parse_buffer
***   self.tags.append(TAGLIST[self.tagID](buffer=buffer))**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 476, in __init__
***   self._parse_buffer(buffer)**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 493, in _parse_buffer
***   tag._parse_buffer(buffer)**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 493, in _parse_buffer
***   tag._parse_buffer(buffer)**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 493, in _parse_buffer
***   tag._parse_buffer(buffer)**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 404, in _parse_buffer
***   self.tags.append(TAGLIST[self.tagID](buffer=buffer))**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 476, in __init__
***   self._parse_buffer(buffer)**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 493, in _parse_buffer
***   tag._parse_buffer(buffer)**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 349, in _parse_buffer
***   length = TAG_Short(buffer=buffer)**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 99, in __init__
***   self._parse_buffer(buffer)**********
*** File I:\Minecraft-Region-Fixer-master\nbt\nbt.py, line 105, in _parse_buffer
***   self.value = self.fmt.unpack(buffer.read(self.fmt.size))[0]**********
*** File C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.496.0_x64__qbz5n2kfra8p0\lib\gzip.py, line 286, in read
***   return self._buffer.read(size)**********
*** File C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.496.0_x64__qbz5n2kfra8p0\lib\_compression.py, line 68, in readinto
***   data = self.read(len(byte_view))**********
*** File C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.496.0_x64__qbz5n2kfra8p0\lib\gzip.py, line 492, in read
***   raise EOFError("Compressed file ended before the "
**********

**Comment by Fenixin** [comment]
Hello!

It looks like the .dat file is corrupted. Try removing it, the scan should continue and, probably, finish. 

This is a bug in regionfixer, it should detect this as a corrupted dat file and remove it. I will fix this when I get some time.

Could you please trying to remove the dat file and scanning again?

**Comment by Fenixin** [comment]
Could you send me the problematic dat file?

**Comment by Fenixin** [comment]
I'm going to close this due to inactivity. Feel free to open a new issue if the problem persists.
