### ISSUE TITLE
Missing Entities Tag

### ISSUE THREAD

**Issue by QuestionTuesdayFTW** [Fenixin/Minecraft-Region-Fixer#103]
Hi! Sorry to bother, but I just did a scan of my world since we having chunk and entity issues. Many of my chunks were missing the entities tag. I read through the documentation and did see that this error means that the chunks are missing their NBT structure, but I did see from Issue #75 that the functionality to add the missing tags needed to be added. I was wondering if this functionality has indeed been added. 

Using version 0.3.2. Thanks!

**Comment by Fenixin** [comment]
Hello!

If you run ```python regionfixer.py --help```:

```
...
--fix-missing-tag, --fm           Fixes chunks that have the Entities tag missing. This will add the missing tag.
...
```
Please, try it and tell me if that worked.

**Comment by QuestionTuesdayFTW** [comment]
Hi! Thanks for the quick reply. I completely missed that, I managed to run that and it did end up working. Took a while since I had almost 300,000 chunks missing that, but looks as if everything's working now. Thank you!

**Comment by Fenixin** [comment]
I'm glad it worked, closing ths issue. Feel free to reopen if you have any other problem
