### ISSUE TITLE
Am I doing something wrong? 

### ISSUE THREAD

**Issue by thattony12** [Fenixin/Minecraft-Region-Fixer#107]
I'm pretty sure I did everything right, I have Python 3.7 installed and I downloaded the fixer from you, but nothing seems to happen in the cmd prompt. I wrote it many different ways, with and without spaces, but nothing worked.

Here is a photo of what happens (nothing): ![recibo](https://user-images.githubusercontent.com/62907280/77954672-05258b80-729d-11ea-86dc-ad25f8d589c0.jpg)

Here is a copy of my world. It used to be on a server. https://drive.google.com/file/d/1s6F0Fe9Ypu3wwdMgDJD5rKhANUTelnrq/view?usp=sharing

**Comment by TyeMonkey** [comment]
Same here, it does nothing

**Comment by Fenixin** [comment]
Hello!

I have seen this a few times and I don't know why it happens. There was another user with the same problem that solved it but never reported back.

I have no idea what's going on. Could you please try to run regionfixer writing:
```python regionfixer.py -p 4 --delete-corrupted <your world folder>```

If using python doesn't work try ```python3```

**Comment by Fenixin** [comment]
That said, I will donwload your world and test it just in case is a paroblem in regionfixer.

**Comment by thattony12** [comment]
Still nothing :/

![imagencmd](https://user-images.githubusercontent.com/62907280/78076633-cc58e580-7374-11ea-9236-a2be98e14613.jpg)

**Comment by TyeMonkey** [comment]
same thing here

**Comment by Fenixin** [comment]
That is the strangest thing ever. Can you write some gibberish to see if it throws an error? Can you run anything else in that terminal? Have you restarted your system after installing python?

**Comment by thattony12** [comment]
![image](https://user-images.githubusercontent.com/62907280/78081368-6709f200-737e-11ea-8924-5610e5313f03.png)

I have not restarted my system, I will now though.

**Comment by thattony12** [comment]
Now that I've restarted it, there is a small 2-second pause after a command, but nothing happens.

**Comment by Fenixin** [comment]
Could you try to run python alone? Try:
```python```
```python3```
```python --version```

And report back

**Comment by thattony12** [comment]
like this? sorry I'm a bit unfamiliar to this.

![image](https://user-images.githubusercontent.com/62907280/78145526-ff47bb80-73fe-11ea-92b7-2d7985720844.png)

**Comment by TyeMonkey** [comment]
When I said python in console, it opened up python 3.8 app in microsoft store

**Comment by TyeMonkey** [comment]
I have figured it out, in CMD you have to type 
> python -m pip install SomePackage
To install python into the cmd for it to work

**Comment by thattony12** [comment]
hey... I was able to join the world, with mods too! A lot of the modded blocks are gone, but it works now! I don't know why nothing happened in cmd prompt but I can't complain! thank you!

**Comment by Fenixin** [comment]
@thattony12, I'm glad that you solved your problem.

So this looks like a problem with python path, could you check question/answer?
https://stackoverflow.com/questions/44491802/unable-to-run-python-programs-from-windows-10-cmd

Try it, and if it works I will put it in the wiki, so other people doesn't have to ask the same question. If all of you have solved the problem, please, close the issue.

**Comment by UnrealPinguin** [comment]
Hey, I had the same problem. I typed Python in cmd and it opened the windows store. Install it and it will work. I hope this will solve the problem for other people.

**Comment by Fenixin** [comment]
@UnrealPinguin, thanks very much for the information!

**Comment by Fenixin** [comment]
So this seems to be solved. I have added (and updated) the troubleshooting wiki page to add the windows store idea (thanks a lot @UnrealPinguin). Closing this. Don't hesitate to open another issue if you need anything else.

**Comment by Chucky891** [comment]
how to use python with Using the Minecraft Region Fixer sorry I'm a noob to all this kind of stuff

**Comment by Fenixin** [comment]
@Chucky891, please, read the wiki: https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Usage

If after reading the Usage section you still have problems don't hesitate to open a new issue.
