### ISSUE TITLE
Can't run regionfixer

### ISSUE THREAD

**Issue by Pantonadget** [Fenixin/Minecraft-Region-Fixer#108]
Hi !
I have some issues with a Minecraft world, so i downloaded your package to fix this up !
I'm not used to python, neither other programming tools. 
I'm using Windows, and when i go to cmd and write this down, nothing seems to happen

> 
> Microsoft Windows [version 10.0.18362.720]
> (c) 2019 Microsoft Corporation. Tous droits réservés.
> 
> C:\Users\Maxime>cd desktop
> 
> C:\Users\Maxime\Desktop>cd mcfr
> 
> C:\Users\Maxime\Desktop\Mcfr>python regionfixer.py C:\Users\Desktop\Monde
> 
> C:\Users\Maxime\Desktop\Mcfr>

I unziped the file, which is located in 'Mcfr' in my desktop, and i placed my world named 'Monde' in my desktop too. I have python 3.8 installed. I'm pretty sure the solution is easy, though, i'm missing it. 
Thanks for your time !

**Comment by Fenixin** [comment]
Hello!

This looks like you don't have the python folder in the PATH, please give a look to:
https://stackoverflow.com/questions/44491802/unable-to-run-python-programs-from-windows-10-cmd

Tell me if that works for you.

**Comment by Pantonadget** [comment]
Thanks a lot for your advice, it was as easy as that and it worked !
