### ISSUE TITLE
MCF not Launching on windows 10.

### ISSUE THREAD

**Issue by OkiStuff** [Fenixin/Minecraft-Region-Fixer#115]
**Describe the bug**
When launching any of the .py files it returns a error. I'm using the latest version of python.

**Expected behavior**
It should launch

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.8.2
 - Region Fixer Version: 0.3.2

**Comment by Fenixin** [comment]
Hello!

Well, that is something new. What do you mean with *any* of the .py files? Have you read the articles on [Installation](https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Installation) and [Usage](https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Usage) in the wiki?

Could you please copy, as the bug template indicated, how you run regionfixer and what error does it give you?

**Comment by KryptoX0** [comment]
I'm having this same issue, the command that i ran inside of the regionfixer folder was "python regionfixer.py "C:\Users\KryptoX\Documents\Rustic Server\world". There was no error it just returned nothing

**Comment by Fenixin** [comment]
@KryptoX0, please, give give [this](https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Troubleshooting) a look and report if that solves your issue

**Comment by syntaxxl** [comment]
I'm having the same problem as this guy is. 
I can run everything, but when it comes to regionfixer.py , nothing pops up. 
I opened the --help through CMD too, worked perfectly fine, the only problem is with regionfixer.py.

![image](https://user-images.githubusercontent.com/66563883/85311512-87c87c00-b483-11ea-999e-9b33e30da86f.png)

**Comment by syntaxxl** [comment]
I'm having the same problem as this guy is.
I can run everything, but when it comes to regionfixer.py , nothing pops up.
I opened the --help through CMD too, worked perfectly fine, the only problem is with regionfixer.py.

(Yes, I know I went to another directory, I was testing if .py was working or not)

**Comment by Fenixin** [comment]
I'm going to close this. Please give the branch bugfix a go:
https://github.com/Fenixin/Minecraft-Region-Fixer/tree/bugfix

There is a change that might have fixed this issue.

Don't hesitate to open a new issue if the problem persists
