### ISSUE TITLE
region-fixer says my world doesn't exist

### ISSUE THREAD

**Issue by noplsno** [Fenixin/Minecraft-Region-Fixer#120]
I wanted to scan my Minecraft world, and pointed to the worlds path, but as I pressed Enter, this message appeared:

Warning: The folder C:\Users\User\AppData\Roaming\.minecraft\saves\WorldTwo doesn't exist. I'll skip it.
Error: No worlds or region files to scan!

 - Windows 10
 - Python version: [3.8]
 - Region Fixer Version [v0.3.2]

**Additional context**
Why did this happen? Did I do anything wrong?

**Comment by Fenixin** [comment]
Hello there!

Well, looking at what you provided me I would say that the path to your world is wrong. There seems to be a missing `\` in your path, from this:
```
C:\Users\User\AppData\Roaming.minecraft\saves\WorldTwo
```
To this:
```
C:\Users\User\AppData\Roaming.minecraft\saves\WorldTwo
```

Please, try that and see if that helps.

**Comment by noplsno** [comment]
Sorry for the late reply. I tried it again, with the backslash, but I still get the same massage. There's a space between "World" and "Two", so I made a quotation mark between the words. But it's always the same massage. I copied it from my world folder, and pasted it, so there's no way there's anything wrong now. I made a screenshot of it:
![Screenshot (9)](https://user-images.githubusercontent.com/67023208/85060873-3af45500-b1a6-11ea-9c5a-867945599655.png)

**Comment by Fenixin** [comment]
Now it's my turn: sorry for the late reply. But it's normal that doesn't work, you have to use quotation marks around the world path, like this:
```
python regionfixer.py "C:\User\User\AppData\Roaming\.minecraft\saves\World Two"
```
Try this if you can

**Comment by noplsno** [comment]
Again, sorry for the late reply. I feel stupid for not understanding this correctly. It worked. Thanks for helping an idiot like me.

**Comment by Sickmsue** [comment]
Hi I know this is an old post but I was also facing a similar issue. C:\Users\16619\Desktop\Server backup 1 is the path link I put into the command console. But nothing I keep getting a "No worlds or region files to scan!"

**Comment by Fenixin** [comment]
@Sickmsue, hello! Please, open a new issue using the template and I will help you.

**Comment by Sickmsue** [comment]
> @Sickmsue, hello! Please, open a new issue using the template and I will help you.

Posted one! thank you so much!!

**Comment by chemis11** [comment]
help me
![Captura de pantalla (28)](https://github.com/Fenixin/Minecraft-Region-Fixer/assets/145369858/b7208d40-636c-4b75-8a4f-a4ffd67ac2ab)

**Comment by ViniciosSoder** [comment]
> help me ![Captura de pantalla (28)](https://private-user-images.githubusercontent.com/145369858/268695724-b7208d40-636c-4b75-8a4f-a4ffd67ac2ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDY4MzksIm5iZiI6MTcxMDcwNjUzOSwicGF0aCI6Ii8xNDUzNjk4NTgvMjY4Njk1NzI0LWI3MjA4ZDQwLTYzNmMtNGI3NS04YTRmLWE0ZmZkNjdhYzJhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QyMDE1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTY3ZDNiOTgyMDI1OTc5MmYzY2MwMWVkY2ViNjU4NmRhOTBmOWZlNGE5Y2YzMzk3MDllNjhhOGJjNDAwNTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qM2Fsw1PEhcVOryXnjIMjwq20mbI2U5AQNgHGxKEqTQ)
Same

**Comment by ViniciosSoder** [comment]
> > help me ![Captura de pantalla (28)](https://private-user-images.githubusercontent.com/145369858/268695724-b7208d40-636c-4b75-8a4f-a4ffd67ac2ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDY4MzksIm5iZiI6MTcxMDcwNjUzOSwicGF0aCI6Ii8xNDUzNjk4NTgvMjY4Njk1NzI0LWI3MjA4ZDQwLTYzNmMtNGI3NS04YTRmLWE0ZmZkNjdhYzJhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QyMDE1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTY3ZDNiOTgyMDI1OTc5MmYzY2MwMWVkY2ViNjU4NmRhOTBmOWZlNGE5Y2YzMzk3MDllNjhhOGJjNDAwNTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qM2Fsw1PEhcVOryXnjIMjwq20mbI2U5AQNgHGxKEqTQ)
> > Same

https://github.com/Fenixin/Minecraft-Region-Fixer/issues/147

**Comment by ViniciosSoder** [comment]
> help me ![Captura de pantalla (28)](https://private-user-images.githubusercontent.com/145369858/268695724-b7208d40-636c-4b75-8a4f-a4ffd67ac2ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjIzMzgsIm5iZiI6MTcxNTc2MjAzOCwicGF0aCI6Ii8xNDUzNjk4NTgvMjY4Njk1NzI0LWI3MjA4ZDQwLTYzNmMtNGI3NS04YTRmLWE0ZmZkNjdhYzJhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQwODMzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGEyNTExZDNkYjhjNTE4MDhkZGE3Mjg3Y2RhNmFhNDdjMDA0ZjE4NzkzMmJiNGZlM2I0MGRmMGJjYTAwODE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VEWmojMA9qliXmssaLjUjkRWAcQa9OzuGjJDXY71Qsg)

If adding quotation marks didn't fix for you (as I can see by the print), you can also shorter the path, placing in C:\WorldExample, while removing the spaces within.
