### ISSUE TITLE
Codes

### ISSUE THREAD

**Issue by paulrach** [Fenixin/Minecraft-Region-Fixer#121]
Is there a place where the identity codes of the output are listed?

If you use regionfixer.py -v 

It outputs (c:0, w:  , tme: , so: , mt:, t: ), what do these letter mean?

I've posted here because I can't find a way to contact you.

Thanks

**Comment by Fenixin** [comment]
Hey!

Well, it seems there is not. I will update the wiki with the codes. Meanwhile:
```
c: corrupted
w: wrong located
tme: too many entities
so: shared offset
mt: missing entity tag
t: total
```

I hope that helps.

**Comment by paulrach** [comment]
Thank you. 




That's perfect.




Take care




________________


Paul Clarkson




✉️: paul@pr-clarkson.co.uk







On Tue, Jun 23, 2020 at 9:14 AM +0100, "Alejandro Aguilera" <notifications@github.com> wrote:















Hey!


Well, it seems there is not. I will update the wiki with the codes. Meanwhile:
c: corrupted
w: wrong located
tme: too many entities
so: shared offset
mt: missing entity tag
t: total



I hope that helps.

**Comment by paulrach** [comment]
Hi

 

A final question.

 

t = total.

 

But what does that mean? A total of what? And is there a maximum?

 

Thanks again

 

Paul Clarkson

**Comment by Fenixin** [comment]
All the codes are number of chunks with that state. So `c: 23` means 23 corrupted chunks in the region file. The t stands for total number of chunks, a region file has a maximun of 1024 chunks. So a line like this one:

`(c: 2, w: 1, tme: 0, so: ,mt: 1, t:567 ),`

Means that there are 567 chunks and 2 of them are corrupted 1 has the entities tag missing and all the others are ok.

**Comment by Fenixin** [comment]
The explanation to the codes has been added to the wiki. Closing this.
