### ISSUE TITLE
'regionfixer_core' Module not found error

### ISSUE THREAD

**Issue by TimeTravelerDMC** [Fenixin/Minecraft-Region-Fixer#123]
everytime I try to get my server world fixed I get this error Im a noob to coding so idk if I doing something wrong or not but Im running out of ideas

C:\Users\Matt\Desktop\Minecraft-Region-Fixer-master>python regionfixer.py -p 4 -
-delete-corrupted C:\Users\Matt\Desktop\Modded server\burn noodle
Traceback (most recent call last):
  File "regionfixer.py", line 29, in <module>
    from regionfixer_core import world
ModuleNotFoundError: No module named 'regionfixer_core'

ive tried regionfixer.py without the python in the command still get the same error

 - OS: win8.1
 - Python version: 3.6.5
 - Region Fixer Version 0.3.2 or master I downloaded both

**Comment by Fenixin** [comment]
Hello!

Could you please try to run the branch bugfix? https://github.com/Fenixin/Minecraft-Region-Fixer/tree/bugfix

That should solve the problem

**Comment by TimeTravelerDMC** [comment]
nope same problem 

C:\Users\Matt\Desktop\Minecraft-Region-Fixer-bugfix\Minecraft-Region-Fixer-bugf
x>regionfixer.py -p 4 --delete-corrupted C:\Users\Matt\Desktop\Modded server\bu
n noodle
Traceback (most recent call last):
  File "C:\Users\Matt\Desktop\Minecraft-Region-Fixer-bugfix\Minecraft-Region-Fi
er-bugfix\regionfixer.py", line 29, in <module>
    from regionfixer_core import world
ModuleNotFoundError: No module named 'regionfixer_core'


idk I may of half solved the problem cause I believe its a corrupt chunk in the nether where I havent built anything but Idk if a deleting of the nether dim file would fix the chunk since its basicilly loading an entire new nether I was able to log and escape back to the overworld without tripping the bad chunk if I turned the render distance down

**Comment by Fenixin** [comment]
This looks like there is something wrong with your PATH. Could you try to run regionfixer.py as:
```
python regionfixer.py -p 4 --delete-corrupted "C:\Users\Matt\Desktop\Modded server\bun noodle"
```
The more I look into this, the more it looks like there is something wrong with the python path.

How have you installed python? have you used it in any other scripts? This might sound stupid but, have you tried to restart your system?

**Comment by TimeTravelerDMC** [comment]
I installed it normally idk if theres a specific path for python when you install it  I havent used it before this and yes I have restarted my computer

**Comment by Fenixin** [comment]
When I say python path I mean what is in your PATH variable when you run regionfixer.

More question that may seem stupid, but just to make sure everything is ok. If you look in the directory where regionfixer is, do you see a folder called `regionfixer_core`? If it's there, is there inside a file named `world.py`?

**Comment by Fenixin** [comment]
Could you try to remove the line numer 29 from regionfixer.py and tell me where it breaks?

**Comment by TimeTravelerDMC** [comment]
no idea how to do that could it be that im using Windows CMD to do this or is that normal

**Comment by Fenixin** [comment]
I think a lot of people use windows CMD to do this, so don't know why is this happening.

You can open regionfixer.py with a text editor, notepad in windows (don't use wordpad or word office), and remove the line number 29, that says:

`from regionfixer_core import world`

This won't fix your issue but it will break in a different way, and maybe, I will be able to know what is going on.

**Comment by TimeTravelerDMC** [comment]
so i did that and now its changed from import to scan and then the same reason and I have no line numbers so I just used the find feature and deleted it that saved and saved the file after making an original just incase
 and i tried it with and without "python" and quotes on the MC world path
C:\Users\Matt\Desktop\Minecraft-Region-Fixer-bugfix\Minecraft-Region-Fixer-bugf
x>regionfixer.py -p 4 --delete-corrupted C:\Users\Matt\Desktop\Modded server\bu
n noodle
Traceback (most recent call last):
  File "C:\Users\Matt\Desktop\Minecraft-Region-Fixer-bugfix\Minecraft-Region-Fi
er-bugfix\regionfixer.py", line 29, in <module>
    from regionfixer_core.scan import (console_scan_world,
ModuleNotFoundError: No module named 'regionfixer_core'

**Comment by Fenixin** [comment]
Well, I pretty sure of something, I have no idea what is going on.

Let's try another thing. Add this:
```
import sys
print('\n'.join(sys.path))
```
To the start of regionfixer.py file and run it with `python regionfixer.py` then tell if in the list of directories that prints is the directory where regionfixer is stored.

**Comment by TimeTravelerDMC** [comment]
I guess I did it I was getting synthax error which mean its not right so I placed it after all the info in the code in front of where the first import line is and im still getting

C:\Users\Matt\Desktop\Minecraft-Region-Fixer-bugfix>Python regionfixer.py
Traceback (most recent call last):
  File "regionfixer.py", line 29, in <module>
    from regionfixer_core.scan import (console_scan_world,
ModuleNotFoundError: No module named 'regionfixer_core'

**Comment by TimeTravelerDMC** [comment]
in all honesty my issue is isolated in the nether the game is operable so would you think just deleting the nether dim file in the world folder would fix the broken chunks since its basically reseting the nether

**Comment by Fenixin** [comment]
> 
> 
> in all honesty my issue is isolated in the nether the game is operable so would you think just deleting the nether dim file in the world folder would fix the broken chunks since its basically reseting the nether


Try that deleting the nether. To tell you the truth I ended up more worried about the bug than the your world :P

> 
> I guess I did it I was getting synthax error which mean its not right so I placed it after all the info in the code in front of where the first import line is and im still getting this error
> 
> C:\Users\Matt\Desktop\Minecraft-Region-Fixer-bugfix>Python regionfixer.py
> Traceback (most recent call last):
> File "regionfixer.py", line 29, in
> from regionfixer_core.scan import (console_scan_world,
> ModuleNotFoundError: No module named 'regionfixer_core'

That is strange, if you have pasted that code before the imports after running (and crashing) should have printed a lot of stuff. You could try creating a new file called 'test.py' and writing in it:
```
import sys
print('\n'.join(sys.path))
```

**Comment by TimeTravelerDMC** [comment]
ah now we might be getting somewhere 

C:\Users\Matt\Desktop\Minecraft-Region-Fixer-bugfix>python test.py
C:\Program Files (x86)\SVP 4\mpv64\python36.zip
C:\Program Files (x86)\SVP 4\mpv64

**Comment by Fenixin** [comment]
Yep, there it is your problem. If it only prints those lines your python path is messed up. When you run a python script the path of the application should be in that list. Why is it no? I have no idea.

How did you install your python interpreter? If is not a problem for you/your system, could you try updating python to the latest version and istalling it from the executable that downloads from here https://www.python.org/ ? (in dowload, the button that says python 3.8.4)

**Comment by TimeTravelerDMC** [comment]
I have that exe already is there anything specific I should modify? or should I uninstall it then re-install it

**Comment by Fenixin** [comment]
In your bug report you say that you are using python 3.6.5 but the version in that exe is 3.8.4. One of the two must be wrongo. Could you check running `python --version`?

Also, you could reinstall python and make sure that you check the option to configure the path for you.

**Comment by TimeTravelerDMC** [comment]
I reinstalled and clicked install now not custom and ticked add 3.8 to PATH and started test.py and got more on the path 

C:\Users\Matt\Desktop\Minecraft-Region-Fixer-bugfix>python test.py
C:\Users\Matt\Desktop\Minecraft-Region-Fixer-bugfix
C:\Program Files (x86)\SVP 4\mpv64
C:\Users\Matt\AppData\Local\Programs\Python\Python38-32\python38.zip
C:\Users\Matt\AppData\Local\Programs\Python\Python38-32\DLLs
C:\Users\Matt\AppData\Local\Programs\Python\Python38-32\lib
C:\Users\Matt\AppData\Local\Programs\Python\Python38-32
C:\Users\Matt\AppData\Local\Programs\Python\Python38-32\lib\site-packages

so I tried to start the fixer and got

C:\Users\Matt\Desktop\Minecraft-Region-Fixer-bugfix>python regionfixer.py -p 4 -
-delete-corrupted C:\Users\Matt\Desktop\Modded server\burn noodle
Traceback (most recent call last):
  File "regionfixer.py", line 26, in <module>
    from multiprocessing import freeze_support
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python38-32\lib\multiprocess
ing\__init__.py", line 16, in <module>
    from . import context
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python38-32\lib\multiprocess
ing\context.py", line 6, in <module>
    from . import reduction
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python38-32\lib\multiprocess
ing\reduction.py", line 16, in <module>
    import socket
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python38-32\lib\socket.py",
line 49, in <module>
    import _socket
ImportError: DLL load failed while importing _socket: %1 is not a valid Win32 ap
plication.

so we are progressing

**Comment by Fenixin** [comment]
The path seems to be fixed. Redownload regionfixer (branch bugfix), because I'm pretty sure that is mangled at this point, and try again. I think it will work after that.

**Comment by TimeTravelerDMC** [comment]
redownloaded same error and sometimes im getting the no module found error too but I think im typing something wrong

C:\Users\Matt\Desktop\Minecraft-Region-Fixer-bugfix>python regionfixer.py -p 4 -
-delete-corrupted "C:\Users\Matt\Desktop\Modded server\burn noodle"
Traceback (most recent call last):
  File "regionfixer.py", line 26, in <module>
    from multiprocessing import freeze_support
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python38-32\lib\multiprocess
ing\__init__.py", line 16, in <module>
    from . import context
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python38-32\lib\multiprocess
ing\context.py", line 6, in <module>
    from . import reduction
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python38-32\lib\multiprocess
ing\reduction.py", line 16, in <module>
    import socket
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python38-32\lib\socket.py",
line 49, in <module>
    import _socket
ImportError: DLL load failed while importing _socket: %1 is not a valid Win32 ap
plication.

**Comment by Fenixin** [comment]
Wow, I didn't expect more errors. This is new and agian I don't know what is going on. But I'm going to guess that again is a problem with your system.

First of all try restarting your system, with a little bit of luck is something about that. Also: Is your system 32 or 64bits? Have you installed the apropiate python version (32 or 64bits)?

**Comment by TimeTravelerDMC** [comment]
Ima restart and try again my system is 64bit and i would have to check if its also python 64-bit

**Comment by TimeTravelerDMC** [comment]
yep I dont have 64 bit Ima uninstall the current python install 64 bit then restart

**Comment by TimeTravelerDMC** [comment]
ok now ive got this error 

C:\Users\Matt\Desktop\Minecraft-Region-Fixer-bugfix>python regionfixer.py -p 4 -
-delete-corrupted "C:\Users\Matt\Desktop\Modded server\burn noodle"
Traceback (most recent call last):
  File "regionfixer.py", line 26, in <module>
    from multiprocessing import freeze_support
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python38\lib\multiprocessing
\__init__.py", line 16, in <module>
    from . import context
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python38\lib\multiprocessing
\context.py", line 6, in <module>
    from . import reduction
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python38\lib\multiprocessing
\reduction.py", line 16, in <module>
    import socket
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python38\lib\socket.py", lin
e 49, in <module>
    import _socket
ImportError: Module use of python36.dll conflicts with this version of Python.

the version is 3.8.4 64bit

**Comment by Fenixin** [comment]
You still have some of the old python 3.6 installed somewhere and is cofnlicting with the new python. Uninstall python 3.6 and see if that helps.

**Comment by TimeTravelerDMC** [comment]
ok i didnt delete it python 3.6 is part of another program I use for video smoothing I just removed the entire program from the program files and then tried to boot region fixer and it started finally

**Comment by Fenixin** [comment]
Great! I'm glad it worked!
