### ISSUE TITLE
Problem While Scanning

### ISSUE THREAD

**Issue by Rileyxxx** [Fenixin/Minecraft-Region-Fixer#125]
**Describe the bug**
Everytime I scan the file it crashes.

**Full copied text from the MS-DOS view**
python regionfinder.py C:\Users\riley\Desktop\world
Bug report:

**********
*** Exception while scanning:
*** taiga_meteors.dat
**********
*** Printing the child's traceback:
*** Exception:<class 'ValueError'>read length must be non-negative or -1
**********
*** File C:\Users\riley\Desktop\Minecraft-Region-Fixer-master\regionfixer_core\scan.py, line 746, in scan_data
***   _ = nbt.NBTFile(filename=s.path)**********
*** File C:\Users\riley\Desktop\Minecraft-Region-Fixer-master\nbt\nbt.py, line 628, in __init__
***   self.parse_file()**********
*** File C:\Users\riley\Desktop\Minecraft-Region-Fixer-master\nbt\nbt.py, line 655, in parse_file
***   self._parse_buffer(self.file)**********
*** File C:\Users\riley\Desktop\Minecraft-Region-Fixer-master\nbt\nbt.py, line 493, in _parse_buffer
***   tag._parse_buffer(buffer)**********
*** File C:\Users\riley\Desktop\Minecraft-Region-Fixer-master\nbt\nbt.py, line 493, in _parse_buffer
***   tag._parse_buffer(buffer)**********
*** File C:\Users\riley\Desktop\Minecraft-Region-Fixer-master\nbt\nbt.py, line 350, in _parse_buffer
***   read = buffer.read(length.value)**********
*** File C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\gzip.py, line 292, in read
***   return self._buffer.read(size)
**********
**Expected behavior**
To find the error with the chunk that keeps crashing the server.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.8
 - Region Fixer Version Master version

**Additional context**

**Comment by Fenixin** [comment]
Hello!

You could try to remove the file that is crashing regionfixer and scan again. Could you send me `taiga_meteors.dat` so I can give it a look?

**Comment by Fenixin** [comment]
Closing this. Feel free to open a new issue if you still have problems.

**Comment by cinnikitty** [comment]
Hello, this is still an issue.
taiga_meteors.dat is a file that's from the mod TAIGA (Tinkers alloying addon).
https://www.curseforge.com/minecraft/mc-mods/taiga-tinkers-alloying-addon
I encountered this bug while trying to fix a world from the 1.12.2 minecraft modpack mc eternal version 1.6.2, which was using TAIGA version 1.3.4 
github doesnt allow me to send the file directly, so if the above information isnt enough and you want my own copy of the file then let me know and i can set up a google drive link or smth.
I managed to get around this bug by simply moving the file out of my world and adding it back after.
For anyone that wants to get around this issue the file path to taiga_meteors is approximately: Instances\MC Eternal(or whatever modpack youre using)\saves\the name of your world\data\taiga_meteors.dat
you can get to the modpack folder pretty easily in curseforge by right-clicking your modpack and clicking open folder.
