### ISSUE TITLE
Region fixer won't open

### ISSUE THREAD

**Issue by ElementalMinecraftGaming** [Fenixin/Minecraft-Region-Fixer#127]
**Describe the bug**
Can't get region fixer to open

**Full copied text from the MS-DOS view**
```
C:\Users\User>C:\Users\User\Downloads\Minecraft-Region-Fixer-0.3.3
'C:\Users\User\Downloads\Minecraft-Region-Fixer-0.3.3' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\User>cd C:\Users\User\Downloads\Minecraft-Region-Fixer-0.3.3

C:\Users\User\Downloads\Minecraft-Region-Fixer-0.3.3>regionfixer.py
Traceback (most recent call last):
  File "C:\Users\User\Downloads\Minecraft-Region-Fixer-0.3.3\regionfixer.py", line 24, in <module>
    import argparse
ImportError: No module named argparse

C:\Users\User\Downloads\Minecraft-Region-Fixer-0.3.3>python regionfixer.py "C:\Users\User\Downloads\world"

C:\Users\User\Downloads\Minecraft-Region-Fixer-0.3.3>python regionfixer.py --help

C:\Users\User\Downloads\Minecraft-Region-Fixer-0.3.3>
```

**Expected behavior**
region fixer to open

**Screenshots**

**Files that would help solving the issue**
If possible, the world/files that triggers the error.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Python version: [e.g. 2.7] python 3.0.1
 - Region Fixer Version [e.g. 2.0.1] latest

**Additional context**
Also tried directly opening the file and it wouldn't open either

**Comment by Fenixin** [comment]
Hello!

You did it properly in:

```
C:\Users\User\Downloads\Minecraft-Region-Fixer-0.3.3>regionfixer.py
Traceback (most recent call last):
  File "C:\Users\User\Downloads\Minecraft-Region-Fixer-0.3.3\regionfixer.py", line 24, in <module>
    import argparse
ImportError: No module named argparse
```
But that error is telling you that a needed (argparse) module is not present. The thing is that module comes with python. So, either you pythons installation is broken or you have a veeeery old python (3.0.1 should have installed argparse, I think).

The problem here is your python installation no region fixer. Please, try to reinstall it or fix it. I would say update to python 3.8.5.

**Comment by ElementalMinecraftGaming** [comment]
I re-installed python but it still doesn't work.

**Comment by Fenixin** [comment]
That is not very helpful. Could you provide some mor information? For example:
 - What version of python have you installed?
 - If you run in a terminal `python --version`, what is the output?
 - What is the error message that regionfixer gives you?

**Comment by Fenixin** [comment]
I'm closing this because it looks stale. Feel free to open a new issue if you still need help.
