### ISSUE TITLE
Cannot get interactive mode to work

### ISSUE THREAD

**Issue by uncovery** [Fenixin/Minecraft-Region-Fixer#130]
**Describe the bug**
this command works: 
`python3 ./regionfixer.py -p 4 /home/minecraft/server/worlds_mint/aether`
this however
`python3 ./regionfixer.py -p 4 --interactive /home/minecraft/server/worlds_mint/aether`
or this:
`python3 ./regionfixer.py -p 4 -i /home/minecraft/server/worlds_mint/aether`
return errors:
```
usage: region_fixer [options] <world-path> <other-world-path> ... <region-files> ...
region_fixer: error: unrecognized arguments: --interactive
```
or 
```
usage: region_fixer [options] <world-path> <other-world-path> ... <region-files> ...
region_fixer: error: unrecognized arguments: -i
```

**Expected behavior**
Interactive mode to work...

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Python version: Python 3.6.8
 - Region Fixer Version: v 0.3.3 (cloned today)

Looks like the feature was commented out? 
https://github.com/Fenixin/Minecraft-Region-Fixer/blob/e14efd834d438acff298fb2c7a9ca1b1f55fb566/regionfixer.py#L331
but it's still listed in the wiki:
https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Usage

**Comment by Fenixin** [comment]
Hello!

That's expected. Interactive mode is deprecated since last version. If you run `regionfixer.py --help` you will see that is no longer in the options.

The feature took too much time to keep (at least as the code is right now).

Closing this.
