### ISSUE TITLE
Crash befor Log file is created

### ISSUE THREAD

**Issue by freaki2010** [Fenixin/Minecraft-Region-Fixer#136]
**Describe the bug**
After the tool has analysed that "Too many entities" are in chunks, it crashed and did not create a logfile. Analysed was a world from this [Skyblock Modpack](https://www.technicpack.net/modpack/youtubers-skyworld.1148290). 

**Full copied text from the MS-DOS view**
https://haste.gafert.org/ikizibegeb.coffeescript

**Expected behavior**
I expected a log file to be created so that I know in which chunk there are too many entities.

**Files that would help solving the issue**
Here is the [worldfile](https://next.ender.io/s/GM62SqmjfMZiPTo).
**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Python version: 3.8
 - Region Fixer Version (v 0.3.3)

**Additional context**
Removing the entities worked anyway. A log file would have been good before, so I can see which chunks are affected.
https://haste.gafert.org/ijewiveges.coffeescript

**Comment by Fenixin** [comment]
Thanks for your bug report.

I will give this a look and see what happens. Currently downloading the files.

**Comment by freaki2010** [comment]
Hey, is there any news yet? and were you able to reproduce the error? 
Thanks a lot for your efforts!

**Comment by Fenixin** [comment]
I'm afraid not, busy week. I hope to give it a look tomorrow or in the weekend.

**Comment by Fenixin** [comment]
Thanks again for the beautifully done bug report. This should be fixed in the branch [bugfix](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/bugfix). Feel free to reopen if it's not.
