### ISSUE TITLE
Ran the Region Fixer, said nothing was wrong??

### ISSUE THREAD

**Issue by Kenbio** [Fenixin/Minecraft-Region-Fixer#137]
i ran the region fixer and it said it was scanning and then it said nothing was wrong with my world, so i checked and i still couldn't get into my world (it would crash with "The game crashed whilst exception in server tick loop
Error: java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
Exit Code: -1") i tried deleting and replacing chunks but it just said there were no corrupted chunks.

Is there another problem? How do i fix it? Anything else that would help...

**Comment by freaki2010** [comment]
Maybe it would help if you fill out this formula. 
The developer asks all the questions he needs to know so that he can reproduce the problem as best as possible. This saves him a lot of questions and gives you a quicker answer.
Here is the formula
```
**Describe the bug**
A clear and concise description of what the bug is.

**Full copied text from the MS-DOS view**
Please, include the command used to run regionfixer.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Files that would help solving the issue**
If possible, the world/files that triggers the error.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Python version: [e.g. 2.7]
 - Region Fixer Version [e.g. 2.0.1]

**Additional context**
Add any other context about the problem here.
```

**Comment by Fenixin** [comment]
Yeah, the template for a bug report is very useful. Please, fill it if you can.

**Comment by Kenbio** [comment]
Oh Shoot sorry!! I’ll write another comment thanks for the heads up!

**Comment by Fenixin** [comment]
I'm closing this, feel free to open a new issue with using the template if you need help.
