### ISSUE TITLE
Idk if this has something to to do with your script but all of my files got renamed.

### ISSUE THREAD

**Issue by pixelblob** [Fenixin/Minecraft-Region-Fixer#139]
**Describe the bug**
Every Single file on my pc got renamed with a ".id-B036F172.[259461356@qq.com].259" at the end...

**Full copied text from the MS-DOS view**
N/a

**Expected behavior**
Everything not to be renamed...

**Screenshots**
![image](https://user-images.githubusercontent.com/34137159/97003723-25b87a00-153c-11eb-915e-935fd9cf9794.png)

**Files that would help solving the issue**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: Cant check, pc is fucked...
 - Region Fixer Version Latest

**Additional context**
EVERYTHING, got renamed...

**Comment by Fenixin** [comment]
I'm pretty sure you've got a pretty nice virus in your computer... stay safe!
