### ISSUE TITLE
Can I use this to search for specific items in a world?

### ISSUE THREAD

**Issue by TomLewis** [Fenixin/Minecraft-Region-Fixer#140]
I would like to be able to search for specific named items in a world offline, could this be possible?

**Comment by Fenixin** [comment]
Hello!

I'm afraid not. It has been requested to be able to search and remove specific entities. But not named items (I didn't even knew you could name items). So, sorry, it's not possible.

**Comment by TomLewis** [comment]
Ok thanks for the reply! Most servers name items with color so that we can have special items for Crates, Events etc. My servers 8+ years old and Im trying to hunt down to see how many of an old event weapon we have and where they are!

**Comment by Fenixin** [comment]
I'm closing this. Sorry I couldn't help you, I hope you find a solution somewhere else.
