### ISSUE TITLE
No module named regionfixer_core.bug_reporter

### ISSUE THREAD

**Issue by eja0iq** [Fenixin/Minecraft-Region-Fixer#141]
Traceback (most recent call last):
  File "E:\Server\SkyblockCloud\Minecraft-Region-Fixer-master\regionfixer.py", line 30, in <module>
    from regionfixer_core.bug_reporter import BugReporter
ImportError: No module named regionfixer_core.bug_reporter

**Comment by Fenixin** [comment]
Hello!

This is not very helpful. Could you please use the template for the bug report?

**Comment by kvnxp** [comment]
File "regionfixer.py", line 30, in <module>
    from regionfixer_core.bug_reporter import BugReporter
ImportError: No module named regionfixer_core.bug_reporter


Same Bug

**Comment by Fenixin** [comment]
Again, not very helpful. Could you please try to fill the template for bug report? I'm closing this.

**Comment by 0xpr03** [comment]
It requires python3 and linux may use python2 by default. That's the issue and solution.

**Comment by walterleonardo** [comment]
Fenixin is very picky.
With how easy it is to respond.
Furthermore, it is such a common problem that you don't need a template to see it.
