### ISSUE TITLE
Exception While Scanning 

### ISSUE THREAD

**Issue by WaffleTraits** [Fenixin/Minecraft-Region-Fixer#144]
**Describe the bug**
Was doing a run for fixing chunks when this exception occured while scanning. I suspect that it may be due to certain items being within a particular region, I can send a copy of the region file privately. The server that I am running is on Minecraft 1.16.4 vanilla jar, although it should be noted that the server has run on fabric server jars in the past (none of the mods affected terrain generation though). 

**Full copied text from the MS-DOS view**
```
Bug report:

**********
*** Exception while scanning:
*** r.-2940.1908.mca
**********
*** Printing the child's traceback:
*** Exception:<class 'UnicodeDecodeError'>'utf-8' codec can't decode byte 0xed in position 9: invalid continuation byte
**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/regionfixer_core/scan.py, line 806, in scan_region_file
***   chunk, tup = scan_chunk(region_file,**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/regionfixer_core/scan.py, line 908, in scan_chunk
***   chunk = region_file.get_chunk(*coords)**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/region.py, line 599, in get_chunk
***   return self.get_nbt(x, z)**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/region.py, line 578, in get_nbt
***   nbt = NBTFile(buffer=data)**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 628, in __init__
***   self.parse_file()**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 655, in parse_file
***   self._parse_buffer(self.file)**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 493, in _parse_buffer
***   tag._parse_buffer(buffer)**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 493, in _parse_buffer
***   tag._parse_buffer(buffer)**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 404, in _parse_buffer
***   self.tags.append(TAGLIST[self.tagID](buffer=buffer))**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 476, in __init__
***   self._parse_buffer(buffer)**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 493, in _parse_buffer
***   tag._parse_buffer(buffer)**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 404, in _parse_buffer
***   self.tags.append(TAGLIST[self.tagID](buffer=buffer))**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 476, in __init__
***   self._parse_buffer(buffer)**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 493, in _parse_buffer
***   tag._parse_buffer(buffer)**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 493, in _parse_buffer
***   tag._parse_buffer(buffer)**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 404, in _parse_buffer
***   self.tags.append(TAGLIST[self.tagID](buffer=buffer))**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 345, in __init__
***   self._parse_buffer(buffer)**********
*** File /mnt/sda1/david/Minecraft-Region-Fixer-0.3.3/nbt/nbt.py, line 353, in _parse_buffer
***   self.value = read.decode("utf-8")
**********

```

**Expected behavior**
Should just scan the files as normal without stopping.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 Server
 - Python version: 3.9
 - Region Fixer Version v 0.3.3

**Comment by Fenixin** [comment]
Hello!

This problem should be fixed in the branch bugfix (speaking of which I should probably merge it into master). Could you please try [bugfix ](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/bugfix )and se eif that works?

**Comment by WaffleTraits** [comment]
> Hello!
> 
> This problem should be fixed in the branch bugfix (speaking of which I should probably merge it into master). Could you please try [bugfix ](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/bugfix)and se eif that works?

Will do, I will do so as soon as I am able.

**Comment by WaffleTraits** [comment]
3200 of ~272k region files scanned and no issues so far compared to earlier attempts. Idk if my ryzen 3900x is getting saturated, but it seems to be going pretty slowly even when specifying 8 processes with `-p 8`. It didn't used to be this slow but then again I never got this far before, so it could be normal.

**Comment by Fenixin** [comment]
@WaffleTraits, that world must be huge (how many gigabytes?). When I scan big worlds my usual bottleneck is the hard drive. The big worlds I use to test regionfixer are stored in the mechanical disk, and that usually the problem for me. Still, that world must be huge, so I think it's normal. Think that every region file is around 1024 small zip compressed files... and you have to decompress all of them, that takes time.

**Comment by WaffleTraits** [comment]
@Fenixin yeah it is a pretty big world,over 500 GB in size. Good point about the hard drive thing, I never thought about that before. I'll have to try and fit the world on one of my SSDs and see if it gets any better results. Thanks for the tip.

**Comment by Fenixin** [comment]
This is not yet fixed, but regionfixer now marks these chunks as corrupted in the last version. I'm going to close this because there is a better discussion in #148, thanks for your report.
