### ISSUE TITLE
region-fixer says my world doesn't exist 

### ISSUE THREAD

**Issue by Sickmsue** [Fenixin/Minecraft-Region-Fixer#147]
My Minecraft modded server has been crashing lately and I was told it could be due to a corruption issue. I am currently running the mod New Beginnings.

While trying to scan my files with region fixer I keep coming across the issue "No worlds or region files to scan!"

 C:\Users\16619\Desktop\Server backup 1 is the path link I put into the command console.

 - Windows 10
 - Python version: 3.9
 - Region Fixer Version: v0.3.3

**Additional context**
What am I doing wrong and what can I do in order to fix this!
![Screenshot (13)](https://user-images.githubusercontent.com/77248958/104137202-f998e200-534f-11eb-9186-c226c1010afb.png)

**Comment by StockyWitt** [comment]
Put quotes around the path link: "C:\Users\16619\Desktop\Server backup 1"

**Comment by Fenixin** [comment]
@Sickmsue, yes, as StockyWitt says, you have to put quotations marks around the folder path:
`"C:\Users\16619\Desktop\Server backup 1"`

Did this solve your issue?

**Comment by Fenixin** [comment]
I'm closing this as it's very old, feel free to reopen if you have the need.
