### ISSUE TITLE
no options output should print corrupted chunk name when reporting corrupted chunks

### ISSUE THREAD

**Issue by dbcopas** [Fenixin/Minecraft-Region-Fixer#149]
When running the tool with no options (python3 regionfixer.py <path to world>), the resulting output tells you how many corrupted chunks there are, but doesn't tell you which chunk(s) is/are corrupted. It would be super useful if it did.

**Comment by Fenixin** [comment]
You can use --verbose and --log for that. I'm going to close this. Feel free to reopen if that not solves the issue.
