### ISSUE TITLE
No module named regionfixer_core.bug_reporter

### ISSUE THREAD

**Issue by shrimpeccable** [Fenixin/Minecraft-Region-Fixer#150]
**Describe the bug**
I did all the setup steps, including cd to the region fixer folder. Then, after trying to run region fixer, I would get a sort of error where it's not able to find the "regionfixer.py" file in the folder. It looks like maybe some of the names are different (i.e. regionfixer_core.bug_reporter is bug_reporter.py?), although not entirely sure. Tried to run it multiple times—and reinstalled it. 

**Full copied text from the MS-DOS view**
```
myname@My-MacBook-Air Minecraft-Region-Fixer-master % python regionfixer.py "/Users/myname/Desktop/world\ copy"
Traceback (most recent call last):
  File "regionfixer.py", line 30, in <module>
    from regionfixer_core.bug_reporter import BugReporter
ImportError: No module named regionfixer_core.bug_reporter
```

**Expected behavior**
Expected it to show this text, as it appears in the [usage](https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Usage) part of this github page: 
```
Welcome to Region Fixer!
    (version: 0.2.0)

    ############################################################
    ############## Scanning separate region files ##############
    ############################################################
```
**Screenshots**
Not really any screenshots

**Files that would help solving the issue**
I could send a zip of my world file, but I don't think that's the issue? 

**Desktop (please complete the following information):**
 - OS: iOS
 - Python version: 3.8
 - Region Fixer Version v0.3.3 (or most recent one because I downloaded it from [this link](https://github.com/Fenixin/Minecraft-Region-Fixer/archive/master.zip) today)

**Additional context**
I'm running a server with the world that I want to check. Also, not familiar with python or coding so I'm not sure if I gave the right information.

**Comment by krolik-exe** [comment]
I have the same error using latest ubuntu 20.04

**Comment by Hypocisy** [comment]
You shuld install python3 and use `python3 regionfixer.py "/Users/myname/Desktop/world\ copy"`.

**Comment by Fenixin** [comment]
@Hypocisy, Thanks for the help!

Yes, this issue sounds like you are not running regionfixer with the correct version of python. Could you try to run it with python3? If you want to check your python version try `python --help`

**Comment by shrimpeccable** [comment]
Thanks for the replies! Hmm I do believe I was using python3— python 3.8. I just deleted and redownloaded [python version 3.9.2](https://www.python.org/downloads/). 

It said this when I typed out `python --help`: 
`usage: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python [option] ... [-c cmd | -m mod | file | -] [arg] ...`
So it looks like I _have_ been using an older version... It's weird because I downloaded it straight from the "download python" webpage. How do you update python? Is there a way to know if you've updated it correctly?

So sorry 😅  this has become a python downloading problem.

**Comment by Hypocisy** [comment]
> Thanks for the replies! Hmm I do believe I was using python3— python 3.8. I just deleted and redownloaded [python version 3.9.2](https://www.python.org/downloads/).
> 
> It said this when I typed out `python --help`:
> `usage: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python [option] ... [-c cmd | -m mod | file | -] [arg] ...`
> So it looks like I _have_ been using an older version... It's weird because I downloaded it straight from the "download python" webpage. How do you update python? Is there a way to know if you've updated it correctly?
> 
> So sorry 😅 this has become a python downloading problem.

Hey guy, Your  system has two different versions of python, in Linux and other parts of Linux systems, the python 2 is default included in the system, command `python` just “run the python 2”, when you got the python 3, simple run `python3` and all be good.
(Sorry for my bad English, I am Chinese)

**Comment by shrimpeccable** [comment]
It works now, thank you! I updated python and used `python3` for the command. 
I also got the `No worlds or region files to scan! Use --help for a complete list of options.` error (when it was on my desktop and downloads folders), but when I moved it into my minecraft saves folder it ended up working.
