### ISSUE TITLE
i have to uncorroupt my world

### ISSUE THREAD

**Issue by shubhgehlot** [Fenixin/Minecraft-Region-Fixer#153]
**Describe the bug**

**Full copied text from the MS-DOS view**
Please, include the command used to run regionfixer.

**Expected behavior**

**Screenshots**

**Files that would help solving the issue**
If possible, the world/files that triggers the error.

**Desktop (please complete the following information):**
 - Python version: [e.g. 2.7]
 - Region Fixer Version [e.g. 2.0.1]

**Additional context**

**Comment by Fenixin** [comment]
Hello!

Sorry for the late answer.

I can't do much with the information that you provided, so I'm closing this. Please, don't hesistate to reopen the issue if you can provide more information.
