### ISSUE TITLE
it is not recognized as an internal or external command, executable program or batch file.

### ISSUE THREAD

**Issue by Lucasppozzi** [Fenixin/Minecraft-Region-Fixer#157]
Hello. I have a problem with the minecraft repairman, the cmd does not recognize the command, I saw a tutorial on how to use it but it did not work, this is what the cmd says "is not recognized as an internal or external command,
executable program or batch file ", i have windows 10 Pro

**Comment by Fenixin** [comment]
Hello!

Sorry for the late answer.

Please, try to follow the instructions in [Installation](https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Installation) in the wiki.

I'm closing this, don't hesitate to ask if you need anythingn else.
