### ISSUE TITLE
Can't use gui and region fixer can't find my corrupt chunk

### ISSUE THREAD

**Issue by OiziZ** [Fenixin/Minecraft-Region-Fixer#159]
Hello, I allow myself to contact you here because I have two problems.

The first being that my map has a corrupted chunk:
[21:00:24] [Server thread / FATAL]: Failed to schedule load callback for chunk [167, -191], and region fixer tells me that the map has no problem after scanning it

The second is that I can't use the gui, when that start setup.py:
setup.py ", line 11, in <module>
     import py2exe
ModuleNotFoundError: No module named 'py2exe'

Can you help me ? Thank you !

**Comment by SimonNitzsche** [comment]
either
`python -m pip install py2exe` or `py -m pip install py2exe`

**Comment by Fenixin** [comment]
Hello!

Sorry for the late answer.

The GUI is completely outdated, it's in there just in case some day, in the far future when I have more time, I can update it. But for now you have to use the CLI. If you are still there you could try to use the last version of regionfixer (master v0.3.4). That may fix your problem.

**Comment by Fenixin** [comment]
I'm closing this, feel free to reopen it if you still have the issue.
