### ISSUE TITLE
Nether world error

### ISSUE THREAD

**Issue by MainSEL** [Fenixin/Minecraft-Region-Fixer#162]
**Describe the bug**
As soon as I try to repair a Nether world and replace it with a backup, I get the error (see picture). There is a missing a backslash. Can you please fix the error as soon as possible. I need to repair a nether world very urgently. 

**Full copied text from the MS-DOS view**
regionfixer.py -b C:\Dateien\Backup\world_nether --rc C:\Datein\world_nether

**Expected behavior**
I hoped that all errors will be replaced by the backup and the world will work again.

**Screenshots**
![CMD](https://user-images.githubusercontent.com/84402804/124367132-f0306880-dc54-11eb-9c8a-05a466189260.png)

![FOLDER](https://user-images.githubusercontent.com/84402804/124367135-f58db300-dc54-11eb-8b10-472c3169e2af.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Python version: 3.9
 - Region Fixer Version 0.3.3

**Comment by Fenixin** [comment]
Hello!

Sorry for the late answer. Thanks to a contribution this should be fixed in the last version. Just pull the branch master.

Don't hesitate to reopen the issue if you still have problems.
