### ISSUE TITLE
Bug report: Exception while scanning

### ISSUE THREAD

**Issue by FrapzHaash** [Fenixin/Minecraft-Region-Fixer#170]
PS C:\Users\lraim\Downloads\Minecraft-Region-Fixer-master\Minecraft-Region-Fixer-master> python regionfixer.py "C:\Users\lraim\AppData\Roaming\.minecraft\saves\Hardcore TKZ"

Welcome to Region Fixer!
(v 0.3.4)

############################################################
############################################################

World info:
 - 192 region/level files,
 - 114 POI files,
 - 153 entities files,
 - 3 player files,
 - and 5 data files.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
3 of 3|##########################################################|Time: 0:00:00

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
5 of 5|##########################################################|Time: 0:00:00

--------- Scanning region, POI and entities files ----------
0 of 459|                                                       |ETA:  --:--:--

Ops! Something went really wrong and regionfixer crashed.

Bug report:

**********
*** Exception while scanning:
*** r.-1.-1.mca
**********
*** Printing the child's traceback:
*** Exception:<class 'AssertionError'>Unrecognized scanned chunk in scan_chunk().
**********
*** File C:\Users\lraim\Downloads\Minecraft-Region-Fixer-master\Minecraft-Region-Fixer-master\regionfixer_core\scan.py, line 810, in scan_region_file
***   chunk, tup = scan_chunk(region_file,**********
*** File C:\Users\lraim\Downloads\Minecraft-Region-Fixer-master\Minecraft-Region-Fixer-master\regionfixer_core\scan.py, line 996, in scan_chunk
***   raise AssertionError("Unrecognized scanned chunk in scan_chunk().")

 - OS: Windows 11 - Python version: 3.1
 - Region Fixer Version 0.3.4

**Comment by 734F96** [comment]
Hello !
Is it an 1.18 world ? If it is, Region-Fixer doesn't currently support this version.
You can see WIP support in PR #169.
Have a nice day ! ^^

**Comment by Fenixin** [comment]
Hello!

I have just merged #169 from @734F96. I'm closing this, feel free to open/reopen if you have any problem.
