### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by HamiIkar** [Fenixin/Minecraft-Region-Fixer#172]
it seems like the tool doesnt work for 1.18 worlds

C:\Users\dominik.SCHREINER-IT\Downloads\Minecraft-Region-Fixer-0.3.4>python regionfixer.py C:\Users\dominik.SCHREINER-IT\Downloads\OBLIVION_old

Welcome to Region Fixer!
(v 0.3.4)

############################################################
############################################################

World info:
 - 49 region/level files,
 - 17 POI files,
 - 33 entities files,
 - 4 player files,
 - and 4 data files.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
4 of 4|##########################################################|Time: 0:00:00

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
4 of 4|##########################################################|Time: 0:00:00

--------- Scanning region, POI and entities files ----------
0 of 99|                                                        |ETA:  --:--:--

Ops! Something went really wrong and regionfixer crashed.

Bug report:

**********
*** Exception while scanning:
*** r.-1.-1.mca
**********
*** Printing the child's traceback:
*** Exception:<class 'AssertionError'>Unrecognized scanned chunk in scan_chunk().
**********
*** File C:\Users\dominik.SCHREINER-IT\Downloads\Minecraft-Region-Fixer-0.3.4\regionfixer_core\scan.py, line 810, in scan_region_file
***   chunk, tup = scan_chunk(region_file,**********
*** File C:\Users\dominik.SCHREINER-IT\Downloads\Minecraft-Region-Fixer-0.3.4\regionfixer_core\scan.py, line 996, in scan_chunk
***   raise AssertionError("Unrecognized scanned chunk in scan_chunk().")
**********

 -Windows 10 
 - Python version: 3.10
 - Region Fixer Version 0.3.4

**Comment by 734F96** [comment]
Hello,
1.18 support is currently in PR #169. ^^
Have a nice day !

**Comment by Fenixin** [comment]
Hello!

I have just merged #169 from @734F96. I'm closing this, feel free to open/reopen if you have any problem.
