### ISSUE TITLE
emoji on sign cause chunk status to be corrupted

### ISSUE THREAD

**Issue by MrEDok** [Fenixin/Minecraft-Region-Fixer#177]
**Describe the bug**
When usign a sign with in this case "FIRE" emoji 🔥 it cause chunk status to be corrupted

**Full copied text from the MS-DOS view**
```
############################################################
################# Scan results for: world ##################
############################################################


Unreadable player files:
No problems found.

Unreadable data files:
No problems found.

Chunk problems:
------------------------------
| Problem | Corrupted  Total |
------------------------------
|  Count  |     1      3280  |
------------------------------
```
**Expected behavior**
not mark as corrupted

**Screenshots**
![image](https://user-images.githubusercontent.com/57065626/147883490-30304b2d-d9a9-4cd2-99d4-68b4f74d65f9.png)

**Files that would help solving the issue**
If possible, the world/files that triggers the error.

**Desktop (please complete the following information):**
 - OS: Windows/linux
 - Region Fixer Version tested on o.3.4 and o.3.5

**Additional context**

**Comment by Fenixin** [comment]
Hello!

Thank you very much for you report, this could be really useful because it sounds like a UTF-8 issue, and can provide some more help to solve #148. I have to sit sometime and fix this.

Could you provide a regionfile with this issue?

**Comment by Fenixin** [comment]
Hello!

Thanks for your issue. This has been fixed in the last release.

Closing the issue, don't hesitate to open a new issue if you find anything else.
