### ISSUE TITLE
Nie mo error

### ISSUE THREAD

**Issue by PauloSobieGra** [Fenixin/Minecraft-Region-Fixer#179]
**Describe the bug**
No matter how long i try, I can't get it to work.
It say's that there is no world file to check, or "Nie mo" error.
I am from Poland so it's saying (You Can-)
![obraz_2022-03-09_184622](https://user-images.githubusercontent.com/101282894/157500344-8bc5b345-809b-4b7e-bb71-6d5bb75572bc.png)

 - Windows 10
 - Python 3.10
 - Newest one

**Comment by Fenixin** [comment]
Closing this because of stale.
