### ISSUE TITLE
Data file is corrupted

### ISSUE THREAD

**Issue by rodopoulos1** [Fenixin/Minecraft-Region-Fixer#186]
Welcome to Region Fixer!
(v 0.3.6)

############################################################
  Scanning world: ('C:\\Users\\rodop\\curseforge\\minecraft\\Instances\\RodopoulosTech\\saves', 'rodotechworld')
############################################################

World info:
 - 269 region/level files,
 - 18 POI files,
 - 11 entities files,
 - 2 player files,
 - and 15 data files.

-------------------- Checking level.dat --------------------
[WARNING!]: 'level.dat' is corrupted with the following error/s:
         The data file cannot be read

---------------- Scanning UUID player files ----------------
0 of 2|                                                         |ETA:  --:--:--

Ops! Something went really wrong and regionfixer crashed.

Bug report:

**********
*** Exception while scanning:
*** cee10b93-2bcf-481f-bc04-f0f798de9648.dat
**********
*** Printing the child's traceback:
*** Exception:<class 'zlib.error'>Error -3 while decompressing data: invalid stored block lengths
**********
*** File C:\Users\rodop\Desktop\Minecraft-Region-Fixer-master\regionfixer_core\scan.py, line 750, in scan_data
***   _ = nbt.NBTFile(filename=s.path)**********
*** File C:\Users\rodop\Desktop\Minecraft-Region-Fixer-master\nbt\nbt.py, line 646, in __init__
***   self.parse_file()**********
*** File C:\Users\rodop\Desktop\Minecraft-Region-Fixer-master\nbt\nbt.py, line 672, in parse_file
***   type = TAG_Byte(buffer=self.file)**********
*** File C:\Users\rodop\Desktop\Minecraft-Region-Fixer-master\nbt\nbt.py, line 112, in __init__
***   self._parse_buffer(buffer)**********
*** File C:\Users\rodop\Desktop\Minecraft-Region-Fixer-master\nbt\nbt.py, line 118, in _parse_buffer
***   self.value = self.fmt.unpack(buffer.read(self.fmt.size))[0]**********
*** File C:\Users\rodop\AppData\Local\Programs\Python\Python310\lib\gzip.py, line 301, in read
***   return self._buffer.read(size)**********
*** File C:\Users\rodop\AppData\Local\Programs\Python\Python310\lib\_compression.py, line 68, in readinto
***   data = self.read(len(byte_view))**********
*** File C:\Users\rodop\AppData\Local\Programs\Python\Python310\lib\gzip.py, line 496, in read
***   uncompress = self._decompressor.decompress(buf, size)
**********

**Comment by Fenixin** [comment]
Hello!

Yes, the data file is corrupted, if you don't have a backup is lost. I hope you have one!

I'm closing this, is old and you don't specify what's your problem.

Feel free to open a new issue and use the templates provided so we can help you.
