### ISSUE TITLE
No __main__module in the world folder

### ISSUE THREAD

**Issue by lt-shy-john** [Fenixin/Minecraft-Region-Fixer#188]
Since I originally intended to use Python with PyCharm. So I didn't set up the PATH with Windows, and I can't use this with  command line FYI. When I was trying to use this script, PyCharm says I need to have a main module which I am confused. 

I tested that with my save folder and still the same. 

![image](https://user-images.githubusercontent.com/37952085/212512846-9196dcd5-c122-4430-a9cf-8d5811eec6a0.png)

**Comment by Fenixin** [comment]
Hello!

In the screenshot you provide you are running a command that I don't understand. First you run python.exe and then a what seems to be a folder and finally regionfixer.py. The error that python throws is about that folder...

If you want to run regionfixer in your save folder you should run it following the usage section of the wiki: https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Usage

I'm going to close this issue, feel free to reopen if you have any doubts after reading the Usage section.
