### ISSUE TITLE
How to download and install the 1.16.5 Minecraft Region Fixer

### ISSUE THREAD

**Issue by QWQMUSHU** [Fenixin/Minecraft-Region-Fixer#189]
I have a problem when using the Multiverse-Core plug-in. He prompts me to use the Minecraft Region Fixer to repair my world. My version is 1.16.5 Forge, but I don't know how to download the Minecraft Region Fixer

**Comment by Fenixin** [comment]
Hello!

Please, to install Region Fixer check the article in the wiki: https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Installation.

I'm going to close this, feel free to reopen if you have any doubt.
