### ISSUE TITLE
Allow individual Chunk replacing from backup

### ISSUE THREAD

**Issue by Narimm** [Fenixin/Minecraft-Region-Fixer#24]
At the moment it appears u cannot replace individual chunks unless they are flagged as corrupted.  I would suggest allowing for individual chunk replacement

**Comment by alexbobp** [comment]
With respect, and I understand it'd be more work, but it's absolutely not out of place in a region fixer.  If a chunk is corrupted, the #1 best possible outcome is to restore just the affected chunk from the latest good backup.  This is exactly in line with the situations people use a region fixer for.

**Comment by Fenixin** [comment]
I'm going to close this. There are world editors that are much better suited for the task.
