### ISSUE TITLE
Chunk Traceback Error

### ISSUE THREAD

**Issue by confuser** [Fenixin/Minecraft-Region-Fixer#30]
1.7 Spigot World
Using Windows v0.1.3 exe

------------------ Scanning the Overworld ------------------
*******_**874 / 7944  11% [###                                 ] ETA:  00:21:36
*_\* Error while scanning:
**\*  world\region\r.-9.10.mca

---

**\* Printing the child's Traceback:
**\* Exception: <type 'exceptions.UnicodeDecodeError'> 'utf8' codec can't decode
byte 0xc0 in position 1: invalid start byte

---

**\* File scan.pyc, line 194, in scan_region_file
**\*   None

---

**\* File scan.pyc, line 278, in scan_chunk
**\*   None

---

**\* File nbt\region.pyc, line 539, in get_chunk
**\*   None

---

**\* File nbt\region.pyc, line 524, in get_nbt
**\*   None

---

**\* File nbt\nbt.pyc, line 508, in **init**
**\*   None

---

**\* File nbt\nbt.pyc, line 535, in parse_file
**\*   None

---

**\* File nbt\nbt.pyc, line 391, in _parse_buffer
**\*   None

---

**\* File nbt\nbt.pyc, line 379, in **init**
**\*   None

---

**\* File nbt\nbt.pyc, line 391, in _parse_buffer
**\*   None

---

**\* File nbt\nbt.pyc, line 304, in **init**
**\*   None

---

**\* File nbt\nbt.pyc, line 314, in _parse_buffer
**\*   None

---

**\* File nbt\nbt.pyc, line 379, in **init**
**\*   None

---

**\* File nbt\nbt.pyc, line 391, in _parse_buffer
**\*   None

---

**\* File nbt\nbt.pyc, line 304, in **init**
**\*   None

---

**\* File nbt\nbt.pyc, line 314, in _parse_buffer
**\*   None

---

**\* File nbt\nbt.pyc, line 379, in **init**
**\*   None

---

**\* File nbt\nbt.pyc, line 391, in _parse_buffer
**\*   None

---

**\* File nbt\nbt.pyc, line 379, in **init**
**\*   None

---

**\* File nbt\nbt.pyc, line 391, in _parse_buffer
**\*   None

---

**\* File nbt\nbt.pyc, line 379, in **init**
**\*   None

---

**\* File nbt\nbt.pyc, line 391, in _parse_buffer
**\*   None

---

**\* File nbt\nbt.pyc, line 257, in **init**
**\*   None

---

**\* File nbt\nbt.pyc, line 265, in _parse_buffer
**\*   None

---

**\* File encodings\utf_8.pyc, line 16, in decode
**\*   None

---

Traceback (most recent call last):
  File "region-fixer.py", line 304, in <module>
  File "region-fixer.py", line 194, in main
  File "cmd.pyc", line 142, in cmdloop
  File "cmd.pyc", line 221, in onecmd
  File "interactive.pyc", line 203, in do_scan
  File "scan.pyc", line 118, in scan_world
  File "scan.pyc", line 402, in scan_regionset
scan.ChildProcessException

File in question: https://www.dropbox.com/s/lt44sfxhpt1ypr1/r.-9.10.mca

**Comment by Fenixin** [comment]
A lot has changed since 2014, so I'm closing this as it is outdated.

Feel free to open a new issue if you have more problems.
