### ISSUE TITLE
Out of memory on corrupt region scan

### ISSUE THREAD

**Issue by PM2D** [Fenixin/Minecraft-Region-Fixer#32]
Problem: region fixer hanged, consumed all memory and got killed by kernel oom killer
Minecraft version: 1.7.2
Server log: http://pastebin.com/gtnUgPyx
Corrupt region file: http://pm2d.tk/r.-1.2.mca.zip

**Comment by Fenixin** [comment]
As far as I know this should be already implemented. Right now region-fixer uses the nbt library to look for chunks that are overlapping, so I'm closing this.
