### ISSUE TITLE
Use Releases instead of putting downloads on mediafire

### ISSUE THREAD

**Issue by blha303** [Fenixin/Minecraft-Region-Fixer#39]
You said in the readme that you stopped using github downloads because it was deprecated, but it was just changed to be [releases](https://github.com/Fenixin/Minecraft-Region-Fixer/releases), which is the same thing but it links source to binaries for easier comparison. Mediafire is fine, but it has a whole lot of ads, whereas Github has none.

**Comment by Fenixin** [comment]
Thanks for pointing that out, will fix for upcoming versions.

**Comment by Fenixin** [comment]
Done. Missing only the last windows exe (still trying to make work som stuff in my computer).
