### ISSUE TITLE
Wrong located chunks

### ISSUE THREAD

**Issue by Bronzeteufel** [Fenixin/Minecraft-Region-Fixer#40]
I got a weird issue: After reload one of my chunks moves to another location and there are errors like

[14:39:43] [Chunk I/O Executor Thread-1/ERROR]: Chunk file at 69,-30 is in the wrong location; relocating. (Expected 69, -30, got 73, -28)
[14:39:43] [Chunk I/O Executor Thread-1/ERROR]: Chunk file at 73,-29 is in the wrong location; relocating. (Expected 73, -29, got 73, -28)

in console. So I ran version v. 0.1.3 of your Region-Fixer:

Chunk problems:
-------------------------------------------------------------------
| Problem | Corrupted  Wrong l.  Etities  Shared o.  Total chunks |
-------------------------------------------------------------------
| Counts  |     0         0         0         2         126290    |
-------------------------------------------------------------------

Region problems:
No problems found.

No chunks to delete with status: Corrupted
No chunks to delete with status: Wrong located
No chunks to delete with status: Too many entities

But it doesn't fix this issue. Seems like any chunks are just cloned by another chunk after reloading them.

**Comment by Fenixin** [comment]
Hello!

You have 2 chunks sharing offset. Those 2 chunks can produce the output that you are seeing in your console. Regionfixer is not going to fix your world if you don't specifically tell to do so. Try using "--delete-shared-offset", if you want to remove them or "replace-shared-offset" if you want to replace them (using a backup).

Please, try that and tell me if works.

**Comment by Bronzeteufel** [comment]
Hey, thank you for your answer!
I'm using your fixer from Nitrado (Chunkfix Option in Webinterface) and I can't download the map because of slow connections. Do you know how I can use this parameters with Nitrado Chunkfix?

**Comment by Fenixin** [comment]
I'm afraid I have no idea how to use Nitrado Chunkfix. You probably have to ask to nitrado people on how to do that. I guess that you can contact them somwhere or read some help in their web.

I'm closing this becuase I think I can't answer that. Feel free to reopen if you need anything else.

Good luck!
