### ISSUE TITLE
regionfixer_gui crash

### ISSUE THREAD

**Issue by VileTouch** [Fenixin/Minecraft-Region-Fixer#41]
Nombre del evento de problema:    APPCRASH
  Nombre de la aplicación: regionfixer_gui.exe
  Versión de la aplicación:   0.0.1.0
  Marca de tiempo de la aplicación:    49180193
  Nombre del módulo con errores:   StackHash_0a9e
  Versión del módulo con errores: 0.0.0.0
  Marca de tiempo del módulo con errores:  00000000
  Código de excepción:    c0000005
  Desplazamiento de excepción: 02489602
  Versión del sistema operativo:   6.1.7601.2.1.0.256.48
  Id. de configuración regional:   7178
  Información adicional 1: 0a9e
  Información adicional 2: 0a9e372d3b4ad19135b953a78882e789
  Información adicional 3: 0a9e
  Información adicional 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by Fenixin** [comment]
I'm afraid those lines lines are not very useful to me. Didn't regionfixer gave you a error msg? This looks more like a windows error msg. Does the crash repeats? What are you doing with the GUI when the crash happens? Is there any more information that you can give me?

**Comment by VileTouch** [comment]
that's the only error message i got. no logs, nothing. just blank window on startup and windows spews what i posted. only possible option is to close.

**Comment by Fenixin** [comment]
I don't know what's going on right now. I will give it a look ASAP (don't know when).

Meanwhile, if you really need to use region fixer right now, you can download the python interpreter and the source code and test if that works for you.

**Comment by themobydisk** [comment]
I can reproduce this too.  I downloaded the EXE version of regionfixer 0.2.0 and ran it on a Windows 7 machine with 4GB RAM.  The command-line works, but the GUI crashes immediately.

**Comment by Fenixin** [comment]
Thanks for reporting. Will look to this when I get some free time.

**Comment by wormzjl** [comment]
Same crash here with win7

**Comment by Fenixin** [comment]
Thanks for reporting, I'm not able to spend time improving region-fixer right now (and I won't be able for some time). So, I am afraid this bug is going to stay there for some time.

**Comment by Fasteroid** [comment]
I also seem to have this issue

**Comment by Fenixin** [comment]
The GUI is right now completely outdated and broken. I don't know if I'm going to update it.

The new in dev version of regionfixer can be found at [new2to3](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/new2to3), but still there is no GUI update.

I'm going to leave this open to remember to give a look at the GUI

**Comment by Fenixin** [comment]
The GUI and windows EXE files are still far from updated and there is a new issue about this. I'm going to close this one.
