### ISSUE TITLE
Heads + Spawners

### ISSUE THREAD

**Issue by Johandrex** [Fenixin/Minecraft-Region-Fixer#42]
Add heads and spawners in the entities removal, that'd be awesome. Since heads and spawners easily can crash the server. Especally heads..

**Comment by sigod** [comment]
Not sure if I want to play on server which doesn't have spawners...

**Comment by johandrex** [comment]
Then don't lol, the issue on my server is players having 100 spawners in one chunk.

**Comment by Fenixin** [comment]
Hello!

Thanks for the feature request. As far as I remember heads and spawners are not entities, they are tile entities. That it's something I want to do but is a future thing. Will leave this open and will give it a look when that future is here.
