### ISSUE TITLE
Location of Corrupt chunk

### ISSUE THREAD

**Issue by Azfaloth** [Fenixin/Minecraft-Region-Fixer#47]
Hi,

Is there a command with options that scans and tells me which chunk exactly is corrupt?

I'm sure region fixer has this functionality but I don't know how to do it. I have a map that fails to load with 1.8.8 because it supposedly has 1 corrupt chunk(as found by region fixer). However this map runs fine on 1.8.7 on a live server. This map is about 4 gb so I would like to know which chunk is corrupt so I can attempt a fix on the server itself(regen the chunk from seed etc)

Turning the server off, downloading the map, deleting the corrupt chunk with region fixer and re-uploading means a good few hours of downtime and I would prefer to restore just that particular chunk.

Thank you for this great tool!

Azfaloth

**Comment by Fenixin** [comment]
Hello!

Yes, there is. Use the option ``--log textfile.txt`` or ``-l textfile.txt`` and regionfixer will save a text file with more detailed results. You can also use ``--log -`` and it will print everything in the prompt.

Please, close the issue if you find this answered.

Good luck!

**Comment by Azfaloth** [comment]
Thank you very much for your help and for making this great tool. :)
