### ISSUE TITLE
Is there a log file somewhere? Or, any way to see a detailed list of the detected errors?

### ISSUE THREAD

**Issue by RoyHinkley** [Fenixin/Minecraft-Region-Fixer#48]
For example, how can a user find out which chunks contained which errors?

**Comment by Fenixin** [comment]
This is not the place for questions like this. But no problem

Yes, you can. Look here:

https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Usage 

And search for "log", you will find a small example. Also, the program help is helpful.

Good luck!
