### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by FireController1847** [Fenixin/Minecraft-Region-Fixer#50]
Just a simple one. It's in the 0.2.0v for windows exe download.

https://gyazo.com/ea06f42fb724028a8e88fe030622d708

**Comment by Fenixin** [comment]
Thanks for the bug report, if I end up fixing the gui in the new regionfixer version I will fix it.

**Comment by Fenixin** [comment]
Though the GUI is not going to be updated the typo has been fixed. Closing this.

**Comment by FireController1847** [comment]
lol okay thanks
