### ISSUE TITLE
Should have easy way to report if there is corruption (exit code?)

### ISSUE THREAD

**Issue by rrauenza** [Fenixin/Minecraft-Region-Fixer#55]
I'd like to make conditional backups based on whether there is corruption or not.

The workflow would be something like...

Everytime the minecraft server is started, it first does a corruption check, and if nothing is corrupted, it snapshots the world before starting minecraft.

Then I always know when I have a clean world.

Or it could conditionally email me when it detects the world is corrupted.

It seems like the easiest design choice would be to have an exit code non zero when corruption is found (and not fixed?)

Another way would be to have a simple "World is 100% ok" like message in the log that one could just grep for.

**Comment by Fenixin** [comment]
Thanks for your suggestion (and sorry for the late answer). I think it's a really good idea.

Right now region-fixer uses exit codes but only to tell if the scan was possible (it returns 1 when you try to run it with an old python version or when there are not worlds to scan). It would be easy to add an exit code when the world has any problem.

I don't know if there are any standard exit codes for programs, I could just use exit code 2 for corrupted world. Any idea on this?

**Comment by ryantheleach** [comment]
I tried to google some, generally exit code 0 is success and any other is an error.

So 0 would be that minecraft region fixer ran successfully and was able to provide a sane world.

Anything else is an error, There are some standard exit codes, but they seem to differentiate pretty hard between platforms, and even then finding one that's relevent is going to be difficult.

Classically on linux I believe that any number in the range of 128-255 is a custom error code, that doesn't need to be associated with the standards, so you are free to use those as you wish.

#define ELIBACC         79      /* Can not access a needed shared library */

Seems like it would match linux standard for the python version you need not being available at a guess?

**Comment by rrauenza** [comment]
Now I apologize for my delay -- yes, 0 for success is the main standard because how the script would interact with bash scripts.

Non zero exit codes sometimes follow errno conventions (http://www.thegeekstuff.com/2010/10/linux-error-codes/), but really, as long as you document your error codes, it doesn't really matter.

**Comment by Fenixin** [comment]
This should be easy to implement, but I won't get the time to program this until christmas.

When I implement this I will add a bunch of different codes. If you have any specific case to be covered just say so.

**Comment by Fenixin** [comment]
Exit codes have been implemented in the last commit of the branch new2to3. I hope to make a release with this branch soon. The exit codes are:
 0 - Everythin ok
 1 - Region fixer crashed
 2 - Nothing to scan
 3 - The scan completed succesfully but problems have been found in the world

Closing this.
