### ISSUE TITLE
Trying to get this to run on Ubuntu

### ISSUE THREAD

**Issue by MithrandirCraft** [Fenixin/Minecraft-Region-Fixer#56]
Hi. I'm trying to run your program on Ubuntu like this:
https://hastebin.com/pifutocide.rb
As you can see, I'm not succeding (Mainly due to error). Could I get some orientation? :)
All I did was follow the first couple steps here: https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Usage

Also, there is no exe for windows.

Python 3.5.3
MC: 1.12.1

**Comment by Fenixin** [comment]
Minecraft region fixer doesn't work with python version 3.x. Yoy need version 2.x to run it. Please try again with the correct version of python and report back.

**Comment by Fenixin** [comment]
This is outdated so I'm going to close this.

The new version of regionfixer will only work with python 3.x. You can the dev version in [new2to3](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/new2to3).
