### ISSUE TITLE
Can't run region fixer

### ISSUE THREAD

**Issue by Trinsdar** [Fenixin/Minecraft-Region-Fixer#58]
I can't seem to either run the gui or use the commands in command prompt. when I try to run regionfixer_gui with python I get these 2 errors: https://imgur.com/a/8Vz8y I have both python 2.7 and wxpython installed. As for the command prompt I get this: `'region-fixer.py' is not recognized as an internal or external command, operable program or batch file.` I used this command: `region-fixer.py --help` in this directory: `C:\Users\----\Desktop\Minecraft-Region-Fixer-master>`
I have replaced the username with lines for privacy reasons; the lines are not my real username.

**Comment by Fenixin** [comment]
Hello,

Sorry to hear that. Have your python path in a environmental variable. I that is the case, could you try to run it as follows `python region-fixer.py`?

Tell me if that works.

**Comment by Trinsdar** [comment]
now it says this: https://imgur.com/a/4AzuC

**Comment by Fenixin** [comment]
Sorry, I think it was my fault. Could you please try `python regionfixer.py`, without the `-`?

**Comment by Trinsdar** [comment]
It works now with that command. thanks for the help.

**Comment by Fenixin** [comment]
You are welcome. Closing the issue
