### ISSUE TITLE
GUI will not run on windows 10

### ISSUE THREAD

**Issue by kath660** [Fenixin/Minecraft-Region-Fixer#60]
When trying to run the regionfixer_gui.exe on windows 10, it stops responding before it finishes loading and soon, windows gives me "Region Fixer GUI has stopped working" message. No choice but to close the program. EXE is dated 3/17/2015 and I have the latest version of windows as of this moment.

**Comment by JLLeitschuh** [comment]
Same issue here.

**Comment by Fenixin** [comment]
Yes, I know that but right now it's impossible for me to fix it. Please, use the command line interface instead. I hope to have some time this summer.

**Comment by JLLeitschuh** [comment]
CLI worked awesomely for me. Thanks for the awesome tool

**Comment by Fenixin** [comment]
Closing this, it's old and there is no GUI right now.
