### ISSUE TITLE
IndexError while replacing corrupt chunk from backup

### ISSUE THREAD

**Issue by Cebtenzzre** [Fenixin/Minecraft-Region-Fixer#61]
```
######### Replacing chunks with status: Corrupted ##########

------- New chunk to replace. Coords: x = -9; z = 12 -------
Backup region file found in:
  backups/world-2018-04-14/Test/region/r.-1.0.mca


Ops! Something went really wrong and regionfixer crashed. I can try to send an automatic bug rerpot if you wish.


Do you want to send an anonymous bug report to the region fixer ftp?
(Answering no will print the bug report) [Y/n] 
Couldn't send the bug report!
[Errno -5] No address associated with hostname

Bug report:

<type 'exceptions.IndexError'>
Traceback (most recent call last):
  File "/usr/bin/regionfixer", line 506, in <module>
    value = main()
  File "/usr/bin/regionfixer", line 433, in main
    fixed = w.replace_problematic_chunks(backup_worlds, problem, ent_lim, del_ent)
  File "/usr/lib/python2.7/site-packages/minecraft-region-fixer/regionfixer_core/world.py", line 906, in replace_problematic_chunks
    coords = get_region_coords(backup_region_path.split()[1])
IndexError: list index out of range
```

```
$ regionfixer --version
0.2.1
$ uname -a
Linux My-PC 4.16.8-1-ARCH #1 SMP PREEMPT Wed May 9 11:25:02 UTC 2018 x86_64 GNU/Linux
```

This was on a lightly modded, Forge+Sponge server.
For now I'll delete the chunk and back up the old region file.  It'd be nice if this program worked 100%, but the chunk was in the middle of nowhere on a near-empty testing subworld, so there's no real loss.

**Comment by Routhinator** [comment]
I also just hit this issue on Ubuntu. Error stack is the same. I have the latest master from git on a default install of Ubuntu 18.04

python shows as `2.7.15rc4`

**Comment by Fenixin** [comment]
Thanks for the bug reports. Could you provide a region file with this problem for testing purposes? I won't be able to look into this for a month or so, but I will eventually, region-fixer really needs an update.

**Comment by Routhinator** [comment]
Not positive I still have a copy however I will look.

**Comment by Cebtenzzre** [comment]
Oh, wow, whoops.  Totally forgot about this.  Yeah, a few region files were involved and I backed them all up.  I'll upload them somewhere.

**Comment by Cebtenzzre** [comment]
Here are the region files that had corrupt chunks when the error occurred (I didn't check them individually, but at least one of them triggered this bug).
https://mega.nz/#!jMUQ1JpI!9fO4lA0g_qPhGsEpqxQfSBSbKI3wIkeIqbAJp6ICnvk

Please don't snoop _too_ much, as I'm pretty sure one of these contains the WIP spawn for a (currently) private server world.

I'm happy to say that I shouldn't need this program as much now as the server recently got a dedicated UPS.

**Comment by Fenixin** [comment]
@Cebtenzzre, thanks you very much.

I'm really busy right now, but I hope to give this issue some time this summer, in a month or so.

**Comment by n0099** [comment]
Just change regionfixer_core/world.py line 906 to `coords = get_region_coords(split(backup_region_path)[1])` and it will fixes
FYI:
#44  d4b7af6
https://github.com/Fenixin/Minecraft-Region-Fixer/blob/d4b7af656c4e8e94c8248a49ca1895a7132c792d/regionfixer_core/world.py#L906

**Comment by Fenixin** [comment]
Thanks! I'll look into this in a few weeks.

**Comment by ano95** [comment]
@n0099's fix worked :)

**Comment by Fenixin** [comment]
Thanks for the info. I will include this fix in the next version

**Comment by dasmeisterlein** [comment]
I have a simmilar problem. First I cant get the regionfixer.exe to run on windows 10.. after I tried it on 8.1 it at least startet but then crashed the gui. Then I tried the command line.. and it crashed again. 
Then I read about deleting mca. files wich are smaler than 4000kb after I did that.. the error showed an other mca file everytime I deletet annother one.. I dont know much about programming.. but this seems stupid to continue.. so i stumbled over this thread an well.. I dont know how to open a .pyo file to edit the lines.. so.. I attach the error message.. 
[rf.txt](https://github.com/Fenixin/Minecraft-Region-Fixer/files/2738510/rf.txt)

**Comment by Fenixin** [comment]
This was added some time ago and it's in the new dev version of region fixer, branch [new2to3](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/new2to3), which I hope to release as new version soon (tm). 

I'm closing this. Feel free to open a new issue if something goes wrong.

Thanks a lot for the information and the fix.
