### ISSUE TITLE
No 1.13 support

### ISSUE THREAD

**Issue by LickTheCheese** [Fenixin/Minecraft-Region-Fixer#63]
it crashes with Minecraft 1.13

**Comment by macfreek** [comment]
@Fenixin Please note that Minecraft 1.13 introduced Long Arrays in the NBT format. I'm not sure if that's the source of this bug report (the submitter posted no details whatsoever), but you may want to upgrade to NBT library 1.5.0.

Regards,
Freek

**Comment by Fenixin** [comment]
Thanks forma the headups. I will upadate the library soon.

**Comment by Fenixin** [comment]
@BloomCake, yes, I will update region-fixer in the next weeks

**Comment by bshuler** [comment]
If you need any help/encouragement on this project, know that it is sorely needed right now.

**Comment by cjburkey01** [comment]
This is an extremely important program, I would be greatly appreciative if you updated it.

**Comment by Fenixin** [comment]
Yeah, sorry about neglecting it for so long. I will update it in the next days. At least just a nbt updated version that works in minecraft 1.13

**Comment by Fenixin** [comment]
I have just uploaded the branch 1-3-update. It contains an updated NBT library (thanks so much @macfreek !) and an easy fix for an old issue. It seems to work with minecraft 1.13 perfectly well.

I will update master and make a realease with this branch in a day or so, just in case after some tests it seems really broken or something. If anybody of you could test this new branch it would be great.

**Comment by cjburkey01** [comment]
Thanks :)

**Comment by opsaaaaa** [comment]
awesome

**Comment by BloomCake** [comment]
Hey, what is the status @Fenixin ?
> I will update master and make a realease with this branch in a day or so

**Comment by Fenixin** [comment]
@BloomCake, The branch [1-3-update](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/1-3-update) has, AFAIK, a working version of region fixer for the new format. Right now I'm away from home and I don't have access to my programming computer (and it will be this way for 3 months or so).

Can you use this branch or it doesn't work for you?

**Comment by BloomCake** [comment]
Ah okay, I did not want to use it in the production environment yet, if it has not been released yet. But I'll test this version

**Comment by sirlinium** [comment]
hello, thanks for the 1.13 update, would it be possible to update the .exe ? I do have a lot of trouble to make it work with python...

**Comment by Kanobiya** [comment]
Can you please tell me how to get the percentage of scanning?
I need to use to output to the site.

**Comment by Kanobiya** [comment]
> Can you please tell me how to get the percentage of scanning?
> I need to use to output to the site php.

**Comment by Kanobiya** [comment]
Can I record scan percentages every 3-5 seconds in a .tx file from Python? Then display them using PHP on the site.

**Comment by ryantheleach** [comment]
@Kanobiya Your comments are off-topic for this issue.

**Comment by Fenixin** [comment]
Just made a release with the last version that should work with this and fix a lot of issues. Closing this.
