### ISSUE TITLE
Scanning Error + Memory Error

### ISSUE THREAD

**Issue by Corcustos** [Fenixin/Minecraft-Region-Fixer#65]
Not sure if this is a user error, or an actual error, but I'm having difficulties getting regionfixer to work properly. I either get a MemoryError, or the program gets an exception while scanning a file. 

Screenshots:
[Scanning Error](https://prnt.sc/kwsn8c)
[Memory Error](https://prnt.sc/kwstge)

My world is minecraft version 1.12.2 and was originally a server world, not singleplayer.

In the first screenshot you can see the exact command and process that I'm doing. The second is just a screenshot of the error itself as the same process happens. Any assistance is appreciated.

**Comment by Fenixin** [comment]
That looks like a .dat file completely broken or that contains gigabytes of information compressed inside. Could you send me that world for testing? Could you please check your RAM usage while scanning?

**Comment by Corcustos** [comment]
This is from Sep 20, 5 months ago. I was long since able to resolve my issue, but not with region-fixer. My issue was a mass set of corrupted chunks, which I solved using MCedit. The world is significantly different than what it was. I have 16gb of RAM so I doubt it was that unless for whatever reason it was using ungodly amounts of RAM. The .dat file has seemed fine from the time of the issue to now as well. 
 Either way, the world that it was used on is no longer in the same state so I cannot give it to you to recreate the same circumstances.

**Comment by Fenixin** [comment]
Thanks for your answer and your bug report and sorry (again) for the late answer. If you want to scan new worlds the branch [new2to3](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/new2to3) is a WIP that has all the last changes.

This quite outdated so I'm closing it.
