### ISSUE TITLE
Error: Exception:<type 'exceptions.KeyError'>'Tag Entities does not exist

### ISSUE THREAD

**Issue by Gerlif** [Fenixin/Minecraft-Region-Fixer#67]
Using the 1.13 update branch:
```

[Errno 11001] getaddrinfo failed

Bug report:

**********
*** Exception while scanning:
*** r.1.0.mca
**********
*** Printing the child's traceback:
*** Exception:<type 'exceptions.KeyError'>'Tag Entities does not exist'
**********
*** File C:\MC\RG\regionfixer_core\scan.py, line 695, in scan_region_file
***   entity_limit)**********
*** File C:\MC\RG\regionfixer_core\scan.py, line 781, in scan_chunk
***   num_entities = len(chunk["Level"]["Entities"])**********
*** File C:\MC\RG\nbt\nbt.py, line 530, in __getitem__
***   raise KeyError("Tag %s does not exist" % key)
**********
```

**Comment by MineDoubleSpace** [comment]
Same issue. Worked with some 1.13 worlds but I am having issues running region fixer on 1.13.2 worlds.

**Comment by rrauenza** [comment]
Similar issue w/ 1.13.2:

I added the type.value to the Exception:

Bug report:

**********
*** Exception while scanning:
*** Mineshaft_index.dat
**********
*** Printing the child's traceback:
*** Exception:<type 'exceptions.ValueError'>Unrecognised tag type: 12
**********
*** File /tmp/Minecraft-Region-Fixer/regionfixer_core/scan.py, line 638, in scan_data 
***   _ = nbt.NBTFile(filename=s.path)**********
*** File /tmp/Minecraft-Region-Fixer/nbt/nbt.py, line 517, in __init__ 
***   self.parse_file()**********
*** File /tmp/Minecraft-Region-Fixer/nbt/nbt.py, line 544, in parse_file 
***   self._parse_buffer(self.file)**********
*** File /tmp/Minecraft-Region-Fixer/nbt/nbt.py, line 391, in _parse_buffer 
***   tag = TAGLIST[type.value](buffer=buffer)**********
*** File /tmp/Minecraft-Region-Fixer/nbt/nbt.py, line 379, in __init__ 
***   self._parse_buffer(buffer)**********
*** File /tmp/Minecraft-Region-Fixer/nbt/nbt.py, line 395, in _parse_buffer 
***   raise ValueError("Unrecognised tag type: %s" % type.value)
**********

**Comment by Fenixin** [comment]
Thanks for the bug report.

Could yoy please send a region file/world with this problem? I will give it a go the next time I'm fixing things.

**Comment by Fenixin** [comment]
I know it's pretty late but you can test the new branch and see if it solves your problem:

https://github.com/Fenixin/Minecraft-Region-Fixer/tree/new2to3

Closing this, feel free to reopen or create a new one.
