### ISSUE TITLE
HELP!!!! CORRUPTED WORLD!

### ISSUE THREAD

**Issue by 1Ghasthunter1** [Fenixin/Minecraft-Region-Fixer#69]
Hello!
I have a world that has somehow been corrupted. Whenever opening it in MCEdit, the screen is blue, but the maps correctly show the world, plus the maps I edited in when the world worked correctly. I tried running it with Region Fixer but it found no issues, and upon opening the world it was just the world and the default seed. Does anyone have a fix? I will also link an attachment to the server file which includes the world. it is the folder 'world' that is corrupt. And, is it possible that the region fixer could fix it correctly?

Also, if you try to run the server(link below), please do not mind all of the error messages in the console. It is an issue not related to the corrupt world file, and I am working on it. It is most likely caused by an outdated plugin. The reason I bring this up is to connect to the server you must spam the connect over and over for about 30 seconds until it lets you in.

Also, by running the server you can see some of the rail system I had, but it is only a section and seems to stop at abrupt walls, as if the chunks are cut off.

Thanks

https://drive.google.com/drive/folders/0B00Guxk1ME_fMDhmTG1nc2tsdzg?usp=sharing

**Comment by Fenixin** [comment]
Hello there!

I have downloaded the world and I will give it a look when I get the time. Thanks!

**Comment by Fenixin** [comment]
Sorry for the very late answer. I have just scanned the world with the very last version of regionfixer, that you can find in [new2to3](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/new2to3), and it only finds a problem, idcounts.dat is corrupted. 

I'm afraid that I don't know anything about the other problems you are talking about. If I had to guess I would say it's more plugin related than world/format related.

I'm closing this, feel free to reopen it if you have any other information about your world or you need anything else. And thanks again for your bug report and your world download.
