### ISSUE TITLE
Invalid slot 'all' 

### ISSUE THREAD

**Issue by MithrandirCraft** [Fenixin/Minecraft-Region-Fixer#70]
We started getting this error:
`[14:19:15 ERROR]: java.lang.IllegalArgumentException: Invalid slot 'all' `
Which results on player's being kicked from the server.
The error possibly makes reference to some item slot effect changes on 1.13.2 (Which I'm not fully aware of)
The issue with the map emerged after I updated it from 1.12.2 to 1.13.2. Now when someone plays for a while on that map, they get kicked, and the error shows up on console.

Attepting at fixing this with Minecraft-Region-Fixer-1-3-update gives no results for any corrupt elements being found... Any ideas on how I could fix this? It does seem like there's something wrong with the world since it happens even deleting everything except the world's region files.

**Comment by MithrandirCraft** [comment]
Yeah this issue is definetly being caused by items with attributes on ALL slots. If I could just fix or remove all of these items from my world...

**Comment by Fenixin** [comment]
Hello there!

Could you send me the smallest possible world that has this problem? As soon as I get some time I try to give it a look.

**Comment by MithrandirCraft** [comment]
Hey @Fenixin. This issue was solved by Spigot with it's updates. If you're really interested in providing solution for such possible issue I can no longer provide a corrupt world. But keep in mind there where some issues with such items when updating maps from 1.12- to 1.13+

In any case, thank you very much for your help! Your tool is very usefull :)
