### ISSUE TITLE
regionfixer.py crash when scanning world as soon as "Scanning region files" begins

### ISSUE THREAD

**Issue by jthigh** [Fenixin/Minecraft-Region-Fixer#76]
Hi - I'm using python3 and executing this command and it crashing as soon as the region scanning bit begins...

Bug report is below..

python3 ./regionfixer.py  -p 4 /minecraft/world          
Welcome to Region Fixer!
(version: 0.3.0)

############################################################
############################################################

World info:
There are 27 region files, 6 player files and 7 data files in the world directory.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
6 of 6|#######################################################################################|Time: 0:00:00

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
7 of 7|#######################################################################################|Time: 0:00:01
------------------ Scanning region files -------------------
0 of 27|                                                                                   |ETA:  --:--:--

**Ops! Something went really wrong and regionfixer crashed.**

Bug report:

<class 'UnboundLocalError'>
Traceback (most recent call last):
  File "./regionfixer.py", line 560, in <module>
    value = main()
  File "./regionfixer.py", line 412, in main
    c.cmdloop()
  File "/usr/lib64/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/ec2-user/Minecraft-Region-Fixer/regionfixer_core/interactive.py", line 208, in do_scan
    o.verbose)
  File "/home/ec2-user/Minecraft-Region-Fixer/regionfixer_core/scan.py", line 579, in console_scan_world
    console_scan_loop(scanners, scan_titles, verbose)
  File "/home/ec2-user/Minecraft-Region-Fixer/regionfixer_core/scan.py", line 513, in console_scan_loop
    logging.debug("\nNew result: {0}\n\nOneliner: {1}\n".format(result,result.oneliner_status))
  File "/home/ec2-user/Minecraft-Region-Fixer/regionfixer_core/world.py", line 310, in oneliner_status
    return stats
UnboundLocalError: local variable 'stats' referenced before assignment

**Comment by TezalTube** [comment]
This might not be much of a help but maybe try running the Windows .EXE version instead (that is, if you're using windows).

**Comment by jthigh** [comment]
This is all LAMP stack stuff... are you suggesting that I copy the world
files to a windows machine and try running the minecraft region fixer
against the world files on a windows machine?

Regards,

Troy
jthigh@gmail.com

**Comment by Fenixin** [comment]
@jthigh, please, don't use the windows exe, It's outdatted. As I said it's a bug and it will be fixed soon.

**Comment by jthigh** [comment]
Alright - thanks for trying to resolve it.

**Comment by Fenixin** [comment]
@jthigh I've just uploaded the branch [fix](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/fix). It's suppossed to fix your problem. Please, tell me if that fixes your problem.

**Comment by jthigh** [comment]
Hi I cloned that 'fix' branch and tried again:

python3 ./regionfixer.py -p 4 /minecraft/world

Welcome to Region Fixer!
(version: 0.3.0)

############################################################
#################  Scanning world: world  ##################
############################################################

World info:
There are 132 region files, 6 player files and 9 data files in the world
directory.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
6 of
6|################################################################################################|Time:
0:00:00

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
9 of
9|################################################################################################|Time:
0:00:02

------------------ Scanning region files -------------------
0 of 132|
                           |ETA:  --:--:--

Ops! Something went really wrong and regionfixer crashed.


Bug report:

<class 'UnboundLocalError'>
Traceback (most recent call last):
  File "./regionfixer.py", line 560, in <module>
    value = main()
  File "./regionfixer.py", line 455, in main
    o.delete_entities, o.verbose)
  File "/home/ec2-user/Minecraft-Region-Fixer/regionfixer_core/scan.py",
line 579, in console_scan_world
    console_scan_loop(scanners, scan_titles, verbose)
  File "/home/ec2-user/Minecraft-Region-Fixer/regionfixer_core/scan.py",
line 513, in console_scan_loop
    logging.debug("\nNew result: {0}\n\nOneliner:
{1}\n".format(result,result.oneliner_status))
  File "/home/ec2-user/Minecraft-Region-Fixer/regionfixer_core/world.py",
line 310, in oneliner_status
    return stats
UnboundLocalError: local variable 'stats' referenced before assignment

Regards,

jthigh@gmail.com

**Comment by Fenixin** [comment]
Could you please check that you are using the correct branch? As far as I can see you are still in branch master because as the Traceback says:

```
line 310, in oneliner_status
    return stats
```

since the last commit that line of code is no longer in line 310, so I think that you haven't switched branches properly.

**Comment by Fenixin** [comment]
I'm going to close this, feel free to open a new issue if you still have problems
