### ISSUE TITLE
regionfixer.exe crash during replacing corrupt chunks when scanning structures 

### ISSUE THREAD

**Issue by TezalTube** [Fenixin/Minecraft-Region-Fixer#77]
After testing with both the overworld and the nether the program appears to crash once it encounters a structure (ie. desert temple, village)

Overworld:
############################################################
############################################################

World info:
There are 784 region files, 0 player files and 18 data files in the world directory.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
Info: No files to scan.

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------

Ops! Something went really wrong and regionfixer crashed. I can try to send an automatic bug rerpot if you wish.

Do you want to send an anonymous bug report to the region fixer ftp?
(Answering no will print the bug report) [Y/n] n

Bug report:

**********
*** Exception while scanning:
*** Temple_index.dat
**********
*** Printing the child's traceback:
*** Exception:<type 'exceptions.ValueError'>Unrecognised tag type
**********
*** File regionfixer_core\scan.pyo, line 637, in scan_data
***   None**********
*** File nbt\nbt.pyo, line 517, in __init__
***   None**********
*** File nbt\nbt.pyo, line 544, in parse_file
***   None**********
*** File nbt\nbt.pyo, line 391, in _parse_buffer
***   None**********
*** File nbt\nbt.pyo, line 379, in __init__
***   None**********
*** File nbt\nbt.pyo, line 395, in _parse_buffer
***   None
**********

Nether:
############################################################
############################################################

World info:
There are 210 region files, 0 player files and 18 data files in the world directory.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
Info: No files to scan.

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
Scanning:  2 / 18  11% [####                                   ] ETA:  00:00:00

Ops! Something went really wrong and regionfixer crashed. I can try to send an automatic bug rerpot if you wish.

Do you want to send an anonymous bug report to the region fixer ftp?
(Answering no will print the bug report) [Y/n] y
Couldn't send the bug report!
[Errno 11001] getaddrinfo failed

Bug report:

**********
*** Exception while scanning:
*** Fortress_index.dat
**********
*** Printing the child's traceback:
*** Exception:<type 'exceptions.ValueError'>Unrecognised tag type
**********
*** File regionfixer_core\scan.pyo, line 637, in scan_data
***   None**********
*** File nbt\nbt.pyo, line 517, in __init__
***   None**********
*** File nbt\nbt.pyo, line 544, in parse_file
***   None**********
*** File nbt\nbt.pyo, line 391, in _parse_buffer
***   None**********
*** File nbt\nbt.pyo, line 379, in __init__
***   None**********
*** File nbt\nbt.pyo, line 395, in _parse_buffer
***   None
**********

**Comment by Fenixin** [comment]
Have you tried the  new version of region-fixer? Have you solved your issue?

**Comment by Fenixin** [comment]
I'm going to close this, feel free to open a new issue if you still have issues.
