### ISSUE TITLE
Regionfixer stuck q_q

### ISSUE THREAD

**Issue by MithrandirCraft** [Fenixin/Minecraft-Region-Fixer#78]
MC 1.13
This is all I get when running the shown command on your latest push with Ubuntu:

![imagen](https://user-images.githubusercontent.com/6623704/57402773-5554b480-71d8-11e9-8ed6-e383138d1e18.png)

The regionfixer works fine with an older version, but It gets stuck with the world I'm trying to scan:

![imagen](https://user-images.githubusercontent.com/6623704/57402850-81703580-71d8-11e9-96da-b838c1ac599f.png)

The issue report was sent btw.

**Comment by Fenixin** [comment]
The new version of region fixer needs python 3 in order to work. I think that you are running it with python 2, please, try with python 3 and report back.

**Comment by MithrandirCraft** [comment]
It runs better, allthough it says there's chunk errors, but after deleting corrupt chunks the errors are still present in further scans. That's odd.

I won't be looking too much into it for now though, it's good enough that it runs :)
