### ISSUE TITLE
Unrecognised tag type

### ISSUE THREAD

**Issue by ArbitraryMoniker** [Fenixin/Minecraft-Region-Fixer#79]
I get the following error when running v 0.2.0 on a java world of mine

```
Bug report:

**********
*** Exception while scanning:
*** Temple_index.dat
**********
*** Printing the child's traceback:
*** Exception:<type 'exceptions.ValueError'>Unrecognised tag type
**********
*** File regionfixer_core\scan.pyo, line 637, in scan_data
***   None**********
*** File nbt\nbt.pyo, line 517, in __init__
***   None**********
*** File nbt\nbt.pyo, line 544, in parse_file
***   None**********
*** File nbt\nbt.pyo, line 391, in _parse_buffer
***   None**********
*** File nbt\nbt.pyo, line 379, in __init__
***   None**********
*** File nbt\nbt.pyo, line 395, in _parse_buffer
***   None
**********
```

Error comes up for any *_index.dat file, and if I delete all those, starts coming up for the .mca files: 

```
Bug report:

**********
*** Exception while scanning:
*** r.-3.-4.mca
**********
*** Printing the child's traceback:
*** Exception:<type 'exceptions.ValueError'>Unrecognised tag type
**********
*** File regionfixer_core\scan.pyo, line 694, in scan_region_file
***   None**********
*** File regionfixer_core\scan.pyo, line 778, in scan_chunk
***   None**********
*** File nbt\region.pyo, line 567, in get_chunk
***   None**********
*** File nbt\region.pyo, line 552, in get_nbt
***   None**********
*** File nbt\nbt.pyo, line 517, in __init__
***   None**********
*** File nbt\nbt.pyo, line 544, in parse_file
***   None**********
*** File nbt\nbt.pyo, line 391, in _parse_buffer
***   None**********
*** File nbt\nbt.pyo, line 379, in __init__
***   None**********
*** File nbt\nbt.pyo, line 391, in _parse_buffer
***   None**********
*** File nbt\nbt.pyo, line 379, in __init__
***   None**********
*** File nbt\nbt.pyo, line 395, in _parse_buffer
***   None
**********
```

World is located here: https://www.dropbox.com/s/qr9mhynee8p0bai/SeanWorld.zip?dl=0

World is very old, have brought forward from beta days. 

Any advice would be appreciated, super old world that a few friends have built over the years, these bugs are making it unplayable :(

**Comment by Fenixin** [comment]
Hello!

So you are running region fixer v0.2.0 in a old world that runs in a new 1.13 minecraft server? If that is the case you are running a old world that has been converted to the new minecraft world format, and that means that you need the last region fixer.

Could you please try to download the newest version of region fixer and scan again? [Here you have a link to the current release](https://github.com/Fenixin/Minecraft-Region-Fixer/releases/tag/v0.3.0)

Could I ask you where have you downloaded that very outdatted version of region fixer?

**Comment by ArbitraryMoniker** [comment]
Whoa, thanks for the quick reply, really didn't expect that!!

I'm going to go and see if I can figure out how to run the python script,
but didn't want to leave you hanging. I'll email you back and let you know
results, but I downloaded the 0.2.0 version here:
https://github.com/Fenixin/Minecraft-Region-Fixer/

In the following area:
Windows .exe downloads

The window executable is generated using py2exe and is the choice if you
don't want to install python in your system.

These downloads were usually in the downloads section of github, but github
has deprecated this feature. So, from Region Fixer v0.1.0 downloads are
stored in mediafire:

http://www.mediafire.com/?1exub0d8ys83y or http://adf.ly/HVHGu (if you want
to contribute a little)

**Comment by Fenixin** [comment]
Ahhh, I completely forgot to update that part of the readme. There is no windows exe right now, I tried to to make one but I failed miserably. I will try again in some time If I get the chance.

Thanks you for pointing that out. You are not the first person that downloads the windows exe and asks for help so I wanted to know where did you get the info. I will update the readme (and probably I should update the wiki) soon (tm).

**Comment by ArbitraryMoniker** [comment]
Wanted to give you an update, I had other errors come up when running the
python script. I ran 0.3.0 using Windows 10's PowerShell and then CMD, but
sending the same error message from CMD. Hoping this kind of reporting
helps! :)


C:\temp\Minecraft-Region-Fixer-0.3.0>C:\Users\seanb\AppData\Local\Programs\Python\Python37\python.exe
.\regionfixer.py --dc "C:\temp\Minecraft Server 2019 march
backup\SeanWorld\level.dat"


Ops! Something went really wrong and regionfixer crashed.


Bug report:

<class 'TypeError'>
Traceback (most recent call last):
  File ".\regionfixer.py", line 560, in <module>
    value = main()
  File ".\regionfixer.py", line 343, in main
    world_list, regionset = parse_paths(args)
  File "C:\temp\Minecraft-Region-Fixer-0.3.0\regionfixer_core\util.py",
line 210, in parse_paths
    world_list = parse_world_list(world_list)
  File "C:\temp\Minecraft-Region-Fixer-0.3.0\regionfixer_core\util.py",
line 222, in parse_world_list
    w = world.World(d)
  File "C:\temp\Minecraft-Region-Fixer-0.3.0\regionfixer_core\world.py",
line 975, in __init__
    self.scanned_level = ScannedDataFile(None, level_dat_path)
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were
given


C:\temp\Minecraft-Region-Fixer-0.3.0>C:\Users\seanb\AppData\Local\Programs\Python\Python37\python.exe
.\regionfixer.py --help "C:\temp\Minecraft Server 2019 march
backup\SeanWorld\level.dat"
Usage:
region_fixer [options] <world-path> <other-world-path> ... <region-files>
...

Program to check the integrity of Minecraft worlds and fix them when
possible.
It uses NBT by twoolie. Author: Alejandro Aguilera (Fenixin)

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -b <backups>, --backups=<backups>
                        List of backup directories of the Minecraft world to
                        use to fix corrupted chunks and/or wrong located
                        chunks. Warning! Region-Fixer is not going to check
                        ifit's the same world, be careful! This argument can
                        be a comma separated list (but never with spaces
                        between elements!). This option can be only used
                        scanning one world.
  --replace-corrupted, --rc
                        Tries to replace the corrupted chunks using the
backup
                        directories. This option can be only used scanning
one
                        world.
  --replace-wrong-located, --rw
                        Tries to replace the wrong located chunks using the
                        backup directories. This option can be only used
                        scanning one world.
  --replace-entities, --re
                        Tries to replace the chunks with too many entities
                        using the backup directories. This option can be
only
                        used scanning one world.
  --replace-shared-offset, --rs
                        Tries to replace the chunks with a shared offset
using
                        the backup directories. This option can be only
                        usedscanning one world.
  --replace-too-small, --rt
                        Tries to replace the region files that are too small
                        to be actually be a region file using the backup
                        directories. This option can be only used scanning
one
                        world.
  --delete-corrupted, --dc
                        [WARNING!] This option deletes! This option will
                        delete all the corrupted chunks. Used with
--replace-
                        corrupted or --replace-wrong-located it will delete
                        all the non-replaced chunks.
  --delete-wrong-located, --dw
                        [WARNING!] This option deletes!The same as --delete-
                        corrupted but for wrong located chunks
  --delete-entities, --de
                        [WARNING!] This option deletes! This option deletes
                        ALL the entities in chunks with more entities than
                        --entity-limit (300 by default). In a Minecraft
                        entities are mostly mobs and items dropped in the
                        ground, items in chests and other stuff won't be
                        touched. Read the README for more info. Region-Fixer
                        will delete the entities while scanning so you can
                        stop and resume the process
  --delete-shared-offset, --ds
                        [WARNING!] This option deletes! This option will
                        delete all the chunk with status shared offset. It
                        will remove the region header for the false chunk,
                        note that you don't loos any chunk doing this.
  --delete-missing-tag, --dmt
                        [WARNING!] This option deletes! Removes any chunks
                        with the mandatory entities tag missing.
  --fix-missing-tag, --fm
                        Fixes chunks that have the Entities tag missing.
This
                        will add the missing tag.
  --delete-too-small, --dt
                        [WARNING!] This option deletes! Removes any region
                        files found to be too small to actually be a region
                        file.
  --entity-limit=ENTITY_LIMIT, --el=ENTITY_LIMIT
                        Specify the limit for the --delete-entities option
                        (default = 300).
  -p PROCESSES, --processes=PROCESSES
                        Set the number of workers to use for scanning.
                        (default = 1, not use multiprocessing at all)
  -v, --verbose         Don't use a progress bar, instead print a line per
                        scanned region file with results information. The
                        letters mean c: corrupted; w: wrong located; t:
total
                        of chunks; tme: too many entities problem
  -i, --interactive     Enter in interactive mode, where you can scan, see
the
                        problems, and fix them in a terminal like mode
  -l SUMMARY, --log=SUMMARY
                        Saves a log of all the problems found in the
specified
                        file. The log file contains all the problems found
                        with this information: region file, chunk
coordinates
                        and problem. Use '-' as name to show the log at the
                        end of the scan.

Copyright (C) 2011  Alejandro Aguilera (Fenixin)
https://github.com/Fenixin/Minecraft-Region-Fixer This program comes with
ABSOLUTELY NO WARRANTY; for details see COPYING.txt. This is free software,
and you are welcome to redistribute it under certain conditions; see
COPYING.txt for details.
Traceback (most recent call last):
  File ".\regionfixer.py", line 560, in <module>
    value = main()
  File ".\regionfixer.py", line 317, in main
    (options, args) = parser.parse_args()
  File
"C:\Users\seanb\AppData\Local\Programs\Python\Python37\lib\optparse.py",
line 1387, in parse_args
    stop = self._process_args(largs, rargs, values)
  File
"C:\Users\seanb\AppData\Local\Programs\Python\Python37\lib\optparse.py",
line 1427, in _process_args
    self._process_long_opt(rargs, values)
  File
"C:\Users\seanb\AppData\Local\Programs\Python\Python37\lib\optparse.py",
line 1501, in _process_long_opt
    option.process(opt, value, values, self)
  File
"C:\Users\seanb\AppData\Local\Programs\Python\Python37\lib\optparse.py",
line 785, in process
    self.action, self.dest, opt, value, values, parser)
  File
"C:\Users\seanb\AppData\Local\Programs\Python\Python37\lib\optparse.py",
line 808, in take_action
    parser.exit()
  File
"C:\Users\seanb\AppData\Local\Programs\Python\Python37\lib\optparse.py",
line 1559, in exit
    sys.exit(status)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\regionfixer.py", line 587, in <module>
    sys.exit(value)
NameError: name 'value' is not defined

C:\temp\Minecraft-Region-Fixer-0.3.0>

**Comment by Fenixin** [comment]
Regionfixer doesn't expect to be pointed to a .dat file. It expects a list of region files or a world directory. Right now there no way to check a single isolated .dat file.

That said, that is definitely a bug. Regionfixer should not crash when you give it a dat file as workload.

Please, try again with a world folder or some region files. If you want to scan that dat file, just scan the world that contains it.

**Comment by ArbitraryMoniker** [comment]
That worked! Now to go and test the file. Here's the results (I tried
repairing a few different backups)

Now I gotta go and test it and see if it gives me the same issue of booting
people off the multiplayer server. Hoping this resolved. Thanks for
your help getting it running!


C:\temp\Minecraft-Region-Fixer-0.3.0>C:\Users\seanb\AppData\Local\Programs\Python\Python37\python.exe
.\regionfixer.py --dc --dw --de --ds --dmt "C:\temp\Minecraft Server
2016\SeanWorld"

Welcome to Region Fixer!
(version: 0.3.0)

############################################################
###############  Scanning world: SeanWorld  ################
############################################################

World info:
There are 567 region files, 37 player files and 990 data files in the world
directory.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
37 of 37|########################################################|Time:
0:00:00

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
990 of 990|######################################################|Time:
0:00:05

------------------ Scanning region files -------------------
567 of 567|######################################################|Time:
0:01:31


############################################################
############### Scan results for: SeanWorld ################
############################################################


Unreadable player files:
No problems found.

Unreadable data files:
idcounts.dat

Chunk problems:
------------------------------------------
| Problem | Missing Entities tag  Total  |
------------------------------------------
|  Count  |          1            114562 |
------------------------------------------

Region problems:
No problems found.


No chunks to delete with status: Corrupted
No chunks to delete with status: Wrong located
No chunks to delete with status: Too many entities
No chunks to delete with status: Sharing offset

#### Deleting chunks with status: Missing Entities tag #####
 Deleting chunks in region set "region":
Removed 1 chunks in this regionset.

 Deleting chunks in region set "DIM-1":
Removed 0 chunks in this regionset.

 Deleting chunks in region set "DIM1":
Removed 0 chunks in this regionset.


Deleted 1 chunks with status: Missing Entities tag

**Comment by Fenixin** [comment]
And it seems that you have found another bug, heh. It doesn't count properly the deleted chunks. Thanks for the report. I will leave this open and fix it.

Also, I'm going to edit your comments to make the tracebacks and reports from regionfixer easier to read.

**Comment by Fenixin** [comment]
Or maybe I'm not, because email replies do not support markdown.

**Comment by Fenixin** [comment]
So, I think I've got all this fixed and it will be pushed soon to master. If you need anything else don't hesitate to reopen.
