### ISSUE TITLE
Crash Scan

### ISSUE THREAD

**Issue by LeanPurp** [Fenixin/Minecraft-Region-Fixer#80]
Hi, I tried to run region fixer for one of my worlds I believe is corrupt, however I keep getting crashes. Can anyone help me please? 
```

C:\WINDOWS\system32>cd C:\Users\Sammy\Downloads\Minecraft-Region-Fixer-v0.2.0

C:\Users\Sammy\Downloads\Minecraft-Region-Fixer-v0.2.0>regionfixer.exe -p 4 --delete-corrupted C:\Users\Sammy\Downloads\MoreQSkyline

Welcome to Region Fixer!
(version: 0.2.0)

############################################################
############  Scanning world: More q (World 1)  ############
############################################################

World info:
There are 27 region files, 0 player files and 4 data files in the world directory.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
Info: No files to scan.

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
Scanning:  4 /  4 100% [#######################################] Time: 00:00:00

------------------ Scanning region files -------------------


Ops! Something went really wrong and regionfixer crashed. I can try to send an automatic bug rerpot if you wish.


Do you want to send an anonymous bug report to the region fixer ftp?
(Answering no will print the bug report) [Y/n] y
Couldn't send the bug report!
[Errno 11001] getaddrinfo failed

Bug report:

**********
*** Exception while scanning:
*** r.-1.0.mca
**********
*** Printing the child's traceback:
*** Exception:<type 'exceptions.ValueError'>Unrecognised tag type
**********
*** File regionfixer_core\scan.pyo, line 694, in scan_region_file
***   None**********
*** File regionfixer_core\scan.pyo, line 778, in scan_chunk
***   None**********
*** File nbt\region.pyo, line 567, in get_chunk
***   None**********
*** File nbt\region.pyo, line 552, in get_nbt
***   None**********
*** File nbt\nbt.pyo, line 517, in __init__
***   None**********
*** File nbt\nbt.pyo, line 544, in parse_file
***   None**********
*** File nbt\nbt.pyo, line 391, in _parse_buffer
***   None**********
*** File nbt\nbt.pyo, line 379, in __init__
***   None**********
*** File nbt\nbt.pyo, line 391, in _parse_buffer
***   None**********
*** File nbt\nbt.pyo, line 379, in __init__
***   None**********
*** File nbt\nbt.pyo, line 395, in _parse_buffer
***   None
**********


C:\Users\Sammy\Downloads\Minecraft-Region-Fixer-v0.2.0>
```

**Comment by LeanPurp** [comment]
@This is the map, it's from a 1.14 realm, and Im trying to get it on my 1.12.2 Forge server
https://www.dropbox.com/s/gxjqcncyedlhqp3/2019-05-23_16-49-27_More%20q%20%28World%201%29.zip?dl=0

**Comment by LeanPurp** [comment]
So I downloaded the new python, and the latest python version of regionfixer and tried to fix the same world but the files are coming up as unreadable? how do I solve this
![image](https://user-images.githubusercontent.com/50964735/58345357-0d789300-7e50-11e9-9afe-12e87c4f0c59.png)

**Comment by Fenixin** [comment]
Hello!

In the wiki you can find: https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Chunk-and-region-problems#unreadable

Unless there is a bug in region-fixer it seems that is a problem on your side. That said, I have downloaded and I will give the world a look in the next days.

I will report back. Please, if you find what's the problem report back.

**Comment by LeanPurp** [comment]
Okay, thank you :)

**Comment by Fenixin** [comment]
Hey! An update, I was wrong. It seems I don't really know my code, and the description in the link I provided you doesn't describe what is really happening with data files. If the data file has status "ureadable" then it could be anything, from permission problems accessing the file to a completely corrupted file.

This is something that should be fixed. so I'm going to leave this open to remind myself to do it sometime.

That said, is there anything more I can help you with?

**Comment by LeanPurp** [comment]
Nothing else dude thank you, just desperate to get back on that map

**Comment by Fenixin** [comment]
A lot has changed since this issue was reported. I'm going to close this, feel free to open a new one if needed.
