### ISSUE TITLE
Entities using same UUID

### ISSUE THREAD

**Issue by kikawet** [Fenixin/Minecraft-Region-Fixer#81]
https://bugs.mojang.com/browse/MC-95649
https://bugs.mojang.com/browse/MC-119971

A way to search/delete/restore entities with the same UUID

**Comment by Fenixin** [comment]
Hello! Thanks for the feature request.

I haven't read the bugs reports yet (I don't know when I will be able to read them). If you really want this as a new feature in region fixer, could you please provide a more detailed explanation? For example:

Summarize what's going on. What's the problem? How can be detected? How could be fixed?

And, something that is really helpful, a world. I won't add a new feature if a don't have a world to test it with. Could you provide a world with this issue so I can test region fixer with it?

**Comment by kikawet** [comment]
Summary: there are two or more entities in the world using the same UUID apparently 

they are created in chunk borders. 

Problem: the game only loads one of them each time so two exist but only one of them "is working".

Fix: remove until there is only one left. All them should be the same  doesn't really matter but maybe there is a proper way to select one of them.

---------------------------------------------------------------------------------------------------------
Example world
[region.zip](https://github.com/Fenixin/Minecraft-Region-Fixer/files/3271778/region.zip)

(You should make a copy of the world before you enter because once you do it you also are going to generate chunks and maybe more entities and loads of terrain)

In the world there are multiple entities only 3 villagers 2 of them with the same UUID in same region different chunk one in chunk 2,19 in world 98,-77 and the other at 2,20 in world 98,-76 

If you open it with mc 1.12.1 one of the villagers is a farmer and the other is in the center the other is a replica of the one farming in the pressure plate, you can see all 3 using mcedit and you can test it in the game because if you pay attention doesn't trigger.

**Comment by Fenixin** [comment]
Thanks you very much, this is really helpful.

I will give this a look hopefully in the next weeks.

**Comment by VADemon** [comment]
Sometimes the duplicate-UUID entity needs to be deleted, sometimes copied/restored. The latter is unusual but may be required (e.g. server worlds).

**Comment by Fenixin** [comment]
This issue is very old, I'm going to close it. Feel free to reopen it if you still have this problem.
