### ISSUE TITLE
Doesn't run in CMD, opens python then tell ms to use regionfixer_gui.py instead.

### ISSUE THREAD

**Issue by doomsdaymatrix** [Fenixin/Minecraft-Region-Fixer#82]
After navigating to folder which region fixer is kept in within cmd, running regionfixer.py opens a python window with:

Minecraft Region Fixer has a command line application and a GUI
(Graphic User Interface) and you have just double clicked the
command line interface. If you really want to run the command line
interface you have to use a command prompt (cmd.exe)

You can also run the GUI, double click regionfixer_gui.py instead!

Press enter to continue:

**Comment by Fenixin** [comment]
Hello!

That is something new! Can I ask what OS are you using? If it's windows, how are you starting the command line interface?

**Comment by doomsdaymatrix** [comment]
Running windows 10. Starting cmd as admin, navigating to folder location,
and attempting to run from there.

**Comment by Fenixin** [comment]
Well, I'm lost, the only thing that can trigger that is that you have a proccess attached to your CLI. And I don't know why that happens. This is the first time this part of the code fails (or at least the first time it fails and somebody reported it). Any idea why is it happening?

If you want to run region fixer no matter what you could modify the line 327 of regionfixer.py from:

```
    if is_bare_console():
```
to
```
    if false:
```
so it never runs that part of the code.

If you are interesting we could test a few things to see what happens, if not the above change will make regionfixer work.

**Comment by doomsdaymatrix** [comment]
I would love to help out.

**Comment by Fenixin** [comment]
I know this issue is old but did you try that code change I suggested? Did it work? If not I will have a few days to work in regionfixer.

**Comment by doomsdaymatrix** [comment]
I did try it. The issue did still persist. Sorry I had never gotten back to
you!

**Comment by Fenixin** [comment]
If you are still interested I have just uploaded a branch called [test_bare](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/test_bare) and it should work for you. If you are no longer interested just tell me and I'll close the issue.

**Comment by Fenixin** [comment]
Closing this, feel free to open a new issue if you still have problems.
