### ISSUE TITLE
Can't fix this world?

### ISSUE THREAD

**Issue by MithrandirCraft** [Fenixin/Minecraft-Region-Fixer#83]
mc 1.13.2

I have an end world with some dragon entity issues.
For some reason there was more than one dragon and the server started to crash once you got near.

I tried fixing it with regionfixer, but the issue doesn't seem to go away, the result is always the same, corrupt chunks always show up with those 7 entities:

![imagen](https://user-images.githubusercontent.com/6623704/59479965-1d87ff00-8e5f-11e9-8aa9-5dcebff86a11.png)

**Comment by Fenixin** [comment]
Hello!

Could you please try to use the `--delete-missing-tag or --dmt` option? As it says those chunks are not corrupted, they don't have the entities tag present.

**Comment by MithrandirCraft** [comment]
I'll try this if I re encounter the issue... for now I just deleted the world :/
