### ISSUE TITLE
Crash when starting region fixer

### ISSUE THREAD

**Issue by mpztilera** [Fenixin/Minecraft-Region-Fixer#84]
mc@vmd34147:~/regionfix/Minecraft-Region-Fixer-0.3.0$ python3 regionfixer.py --help
Traceback (most recent call last):
  File "regionfixer.py", line 29, in <module>
    from regionfixer_core import world
  File "/home/mc/regionfix/Minecraft-Region-Fixer-0.3.0/regionfixer_core/world.py", line 26, in <module>
    from .util import table
  File "/home/mc/regionfix/Minecraft-Region-Fixer-0.3.0/regionfixer_core/util.py", line 27, in <module>
    from . import world
ImportError: cannot import name 'world'

**Comment by Fenixin** [comment]
Well, that is really strange. Could you please try the last release? I've just update the releases page, version v0.3.1 should be there.

**Comment by mpdk** [comment]
If using python2, you will get this error, switch to python 3.6 and it works

**Comment by TonyGravagno** [comment]
Had same issue. Came here and found this ticket. Yes, command "python3" works with the current version. I recommend closing this item. Thanks!!

**Comment by Fenixin** [comment]
Thanks for the comments, I'm going to close this. Please, feel free to reopen or open a new issue if the problem persists.
