### ISSUE TITLE
Some directory names cannot be processed

### ISSUE THREAD

**Issue by omisacma** [Fenixin/Minecraft-Region-Fixer#91]
For Example this directory name:

D:\Minecraft\1ª ERA Minecraftianos\5BK Minecraftianos 16-03-2019 20h58m Reparado\world\region\*.mca

the program only recognizes "Reparado\world\region\*.mca". Seem like spaces and other symbols like "-" can't be recognized...

Windows 10, Python 3.7.4 (64 bits), Minecraft-Region-Fixer 0.3.1

**Comment by Fenixin** [comment]
Hello!

Could you try to put the folder address between quotation marks? Like this:

``"D:\Minecraft\1ª ERA Minecraftianos\5BK Minecraftianos 16-03-2019 20h58m Reparado\world\region*.mca"``

**Comment by omisacma** [comment]
Yes, it works. Is very important that you put this im the usage examples.

Thanks a lot for your awesome and unique tool. It saved my server several times.
________________________________

**Comment by Fenixin** [comment]
Just updated the Wiki/Usages section with the windows folder info. Thanks for the bug report.

I'm closing this, feel free to open a new issue if you have any more problems.
