### ISSUE TITLE
Regionfixer crashed 

### ISSUE THREAD

**Issue by iveltzkamp** [Fenixin/Minecraft-Region-Fixer#94]
Hello, it seems that my world has several corrupt chunks since it "crashed" my server when a user finds it (or that's what I think and it seems to happen). So I decided to scan it with your tool and this is what I got. Can you help me?
I thank you very much and thank you for contributing

World info:
There are 1402 region files, 0 player files and 5 data files in the world directory.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
Info: No files to scan.

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
Scanning:  5 /  5 100% [#######################################] Time: 00:00:00

------------------ Scanning region files -------------------
Scanning: 842 / 1402  60% [#####################               ] ETA:  00:12:43

Ops! Something went really wrong and regionfixer crashed. I can try to send an automatic bug rerpot if you wish.

Do you want to send an anonymous bug report to the region fixer ftp?
(Answering no will print the bug report) [Y/n] Y
Couldn't send the bug report!
[Errno 11001] getaddrinfo failed

Bug report:

**********
*** Exception while scanning:
*** r.16.-3.mca
**********
*** Printing the child's traceback:
*** Exception:<type 'exceptions.ValueError'>Unrecognised tag type
**********
*** File regionfixer_core\scan.pyo, line 694, in scan_region_file
***   None**********
*** File regionfixer_core\scan.pyo, line 778, in scan_chunk
***   None**********
*** File nbt\region.pyo, line 567, in get_chunk
***   None**********
*** File nbt\region.pyo, line 552, in get_nbt
***   None**********
*** File nbt\nbt.pyo, line 517, in __init__
***   None**********
*** File nbt\nbt.pyo, line 544, in parse_file
***   None**********
*** File nbt\nbt.pyo, line 391, in _parse_buffer
***   None**********
*** File nbt\nbt.pyo, line 379, in __init__
***   None**********
*** File nbt\nbt.pyo, line 391, in _parse_buffer
***   None**********
*** File nbt\nbt.pyo, line 379, in __init__
***   None**********
*** File nbt\nbt.pyo, line 395, in _parse_buffer
***   None
**********

**Comment by Fenixin** [comment]
You are using a really old version of regionfixer, maybe you are even using a windows exe (which no longer works). Please report back after downloading the lastest code from [github releases](https://github.com/Fenixin/Minecraft-Region-Fixer/releases/tag/v0.3.2) and running it using python3.

**Comment by iveltzkamp** [comment]
Can I get the latest version of region fixer? Please. This is git-hub cloning

**Comment by iveltzkamp** [comment]
I'm sorry, I found it, I'll try again. Thank you

**Comment by iveltzkamp** [comment]
Can I use any version of python 3.x.x?

**Comment by Fenixin** [comment]
Yes, any python version of python 3.x.x should do the work. Try to get the last one.

**Comment by iveltzkamp** [comment]
Traceback (most recent call last):
  File "C:\Users\Difenileter\Desktop\Minecraft-Region-Fixer-master\regionfixer.py", line 29, in <module>
    from regionfixer_core import world
  File "C:\Users\Difenileter\Desktop\Minecraft-Region-Fixer-master\regionfixer_core\world.py", line 26, in <module>
    from .util import table
  File "C:\Users\Difenileter\Desktop\Minecraft-Region-Fixer-master\regionfixer_core\util.py", line 27, in <module>
    from . import world
ImportError: cannot import name world

**Comment by Fenixin** [comment]
Did you solve your issue?

**Comment by Fenixin** [comment]
Closing this, feel free to open a new issue if you still have problems.
