### ISSUE TITLE
Program doesn't run

### ISSUE THREAD

**Issue by BleesTFE** [Fenixin/Minecraft-Region-Fixer#95]
I have python 3.7.4 installed. I have downloaded a zip and unpacked it into my a folder. When doubleclicking on the .py scripts it opens cmd and immediately closes. Both the regionfixer.py and regionfixer_gui.

Windows 10

**Comment by devomaa** [comment]
x32 or x64? if you dont know go to start menu - (right click or menu) properties and see there

**Comment by BleesTFE** [comment]
I run x64, i think the problem is that my system variables aren't set up properly, trying to fix that right now

**Comment by BleesTFE** [comment]
I'm getting this error when trying to run the program through the cmd:
Traceback (most recent call last):
  File "C:\Users\alluc\Desktop\Region Fixer\Minecraft-Region-Fixer-master\regionfixer_gui.py", line 11, in <module>
    from gui import Starter
  File "C:\Users\alluc\Desktop\Region Fixer\Minecraft-Region-Fixer-master\gui\__init__.py", line 4, in <module>
    from .main import MainWindow
  File "C:\Users\alluc\Desktop\Region Fixer\Minecraft-Region-Fixer-master\gui\main.py", line 4, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

**Comment by BleesTFE** [comment]
Alright, opening cmd, running "python (regionfixer.py script location) (world location)" has worked

**Comment by Fenixin** [comment]
I'm glad it worked. I'm closing this, feel free to open a new issue if there is other problem.
