### ISSUE TITLE
I am doing something wrong?

### ISSUE THREAD

**Issue by luiswenner** [Fenixin/Minecraft-Region-Fixer#97]
I can't run the program at all, I've tried everything. nothing else works

> C:\worlds>regionfixer.py --help

Usage:
region_fixer [options] <world-path> <other-world-path> ... <region-files> ...

no such option: Error: No world paths or region files specified! Use --help for a complete list of options.

C:\worlds>regionfixer.py -p 4 "C:\Users\Anonymous\Desktop\arquivos baixados do servidor\93512\Overworld\broken\region\r.0.0.mca"
Usage:
region_fixer [options] <world-path> <other-world-path> ... <region-files> ...

no such option: Error: No world paths or region files specified! Use --help for a complete list of options.

C:\worlds>regionfixer.py -p 4 "C:\Users\Anonymous\Desktop\arquivos baixados do servidor\93512\Overworld\broken"
Usage:
region_fixer [options] <world-path> <other-world-path> ... <region-files> ...

no such option: Error: No world paths or region files specified! Use --help for a complete list of options.

C:\worlds>

https://pastebin.com/41up2AVj

**Comment by Fenixin** [comment]
I'm really sorry but I don't know what's going on. I have just tried the exact same commands in the exact same version of regionfixer and everything seems to work.

And I can certainly say that my folder structure is stranger than yours, so I think that is not the issue. Still, the only thing I can think of for you to try is to move a region file or a world to a "closer" folder and using quotation marks when writing the folder. I see that you have used them in some of your commands without success, but still is a good thing to do in windows.

Do you have any information of why is this happening? Any strange configuration? Any strange system?

You are not the first person with an issue like this one, so it must be a bug in regionfixer but right now I have no idea what's going on.

**Comment by EncryptSL** [comment]
You must write python regionfixer.py <path_to_world_folder>
Example: python regionfixer.py C:\Users\your_win_name_or_user_acc\Downloads\ServerFolderOrSomething\your_world_folder

**Comment by Fenixin** [comment]
I'm closing this issue, feel free to open a new one if you still have problems.
