### ISSUE TITLE
Cannot run the script

### ISSUE THREAD

**Issue by xzkov** [Fenixin/Minecraft-Region-Fixer#99]
I have Python 3.8 x64 installed on Win7 and taking an error message after trying to run the script:
`C:\Users\MOONLIGHT\Desktop\Minecraft-Region-Fixer-master>py regionfixer.py C:\Users\MOONLIGHT\Desktop\world`
`Traceback (most recent call last):`
`   File "regionfixer.py", line 29, in <module>`
`      from regionfixer_core import world`
`ValueError: source code string cannot contain null bytes`

Can I do something with that? Help please.

**Comment by Fenixin** [comment]
I'm looking ath this (thread)[https://github.com/microsoft/ptvsd/issues/1323#issuecomment-481058988] and it seems to be the same thing. Could you try to remove the *.pyc files created by python? This would help to regenerate them and maybe solves the issue.

**Comment by Fenixin** [comment]
Closing this, feel free to open a new issue if you still have problems
